### ISSUE TITLE
Automation and reproducibility for MLPerf Inference v3.1 and v4.0

### ISSUE THREAD

**Issue by arjunsuresh** [mlcommons/ck#1052]
The [MLCommons taskforce on automation and reproducibility](https://github.com/mlcommons/ck/blob/master/docs/taskforce.md) is helping the community, vendors and submitters check if it is possible to re-run MLPerf inference v3.1 submissions, fix encountered issues and add their implementations to the [MLCommons CM automation to run all MLPerf benchmark implementations in a unified way](https://access.cknowledge.org/playground/?action=scripts).

Note that CM is a collaborative project to run all MLPerf inference benchmarks on any platform with any software/hardware stack using a unified interface. The MLCommons CM interface and automations are being developed based on the feedback from MLPerf users and submitters - if you encounter some issues or have suggestions and feature requests, please report them either via [GitHub issues](https://github.com/mlcommons/ck/issues), via our [Discord channel](https://discord.gg/JjWNWXKxwT) or by providing a patch to [CM automations](https://github.com/mlcommons/ck/tree/master/cm-mlops/script). Thank you and looking forward to collaborating with you!

| Model / Implementation| Reference<br>Intel,Nvidia,AMD,ARM | Nvidia CUDA | Intel | QAIC |  DeepSparse<br>Intel,ARM,AMD | Google TPU |
| --- | --- | --- | --- | --- | --- | --- |
| ResNet50 | ✅ | ✅ | ✅ | ❌<sup>2</sup><br>✅&nbsp;-&nbsp;[via&nbsp;CM](https://github.com/mlcommons/ck/blob/master/cm-mlops/script/reproduce-mlperf-inference-qualcomm/README_aws_dl2q.24xlarge.md) | ✅ | |
| RetinaNet | ✅ | ✅ |  | ❌<sup>2</sup><br>✅&nbsp;-&nbsp;[via&nbsp;CM](https://github.com/mlcommons/ck/blob/master/cm-mlops/script/reproduce-mlperf-inference-qualcomm/README_aws_dl2q.24xlarge.md) | | |
| Bert | ✅ | ✅ | ✅ | ✅ | ✅ | |
| 3d-Unet | ✅ | ✅ |  |  | | |
| RNNT | ✅ | ✅ |  |  | | |
| DLRMv2 |  | ✅ |  | | | |
| GPT-J | ✅| ✅ | ✅ |  | | TBD |
| Stable Diffusion | ✅ | |  |  | | |
| Llama2 |Added to CM - looking for volunteers to test it | |  |  | | |

<sup>1</sup>- original docker container fails because of incompatibility with the latest PIP packages: see [GitHub issue](https://github.com/mlcommons/inference_results_v3.1/issues/11). We collaborate with Intel to integrate their patch with the CM automation and re-run their submissions - it's mostly done.
<sup>2</sup>❌- not possible to rerun and reproduce performance numbers due to missing configuration files: see [GitHub issue](https://github.com/mlcommons/inference_results_v3.1/issues/13). After discussing this issue with submitters, we helped them generate missing configuration files using [MLCommons CM automation for QAIC](https://github.com/mlcommons/ck/blob/master/cm-mlops/script/reproduce-mlperf-inference-qualcomm/README_aws_dl2q.24xlarge.md) and match QAIC performance numbers from v3.1 submission. It should be possible to use CM for QAIC MLPerf v4.0 inference submissions.

# MLCommons CM interface

You should be able to run MLPerf inference benchmarks via unified CM interface and portable workflow that can run natively or inside automatically generated Docker container:
```bash
pip install cmind
cm pull repo mlcommons@ck
cmr "run common mlperf inference" --implementation=nvidia --model=bert-99
```
Prepare official submission for Edge category:
```bash
cmr "run common mlperf inference _submission _full" --implementation=nvidia --model=bert-99
```
Prepare official submission for DataCenter category:
```bash
cmr "run common mlperf inference _submission _full" --implementation=nvidia \
--model=bert-99 --category=datacenter --division=closed
```

**Comment by gfursin** [comment]
We got a feedback from submitters to create a GUI that can generate CM commands. I opened a ticket: https://github.com/mlcommons/ck/issues/1070

**Comment by gfursin** [comment]
[20240130] We had lots of great feedback and improved both generic CM automation recipes and CM workflows for MLPerf inference:
* https://github.com/mlcommons/ck/pull/1078
* https://github.com/mlcommons/ck/pull/1079
We are preparing CM v1.6.1 for the release ...

**Comment by gfursin** [comment]
We started discussing a proposal for MLPerf reproducibility badges similar to ACM/IEEE/NeurIPS conferences: https://github.com/mlcommons/ck/issues/1080 - feedback is welcome!

**Comment by gfursin** [comment]
Following the feedback from the MLPerf submitters, we have developed a prototype of a GUI to generate a command line to run MLPerf inference benchmarks for all main implementations (reference, Intel, Nvidia, Qualcomm, MIL and DeepSparse) and automate submissions. You can check it [here](https://access.cknowledge.org/playground/?action=howtorun&bench_uid=39877bb63fb54725). The long-term goal is to aggregate and encode all MLPerf submission rules and notes for all models, categories and divisions in this GUI.

We have also developed a prototype of a reproducibility infrastructure to keep track of successful MLPerf inference benchmark configurations across different MLPerf versions, hardware, implementations, models and backends based on the [ACM/IEEE/cTuning reproducibility methodology and badging](https://ctuning.org/ae). You can see the last results [here](https://access.cknowledge.org/playground/?action=reproduce&bench_name=benchmark-run-mlperf-inference-v3.1) - we will continue adding more tests based on your suggestions including GPT-J, LLAMA2 and Stable Diffusion.

Our goal is to test as many v4.0 submissions as possible and add them to the above GUI to make it easier for the community to rerun experiments after the publication date. If some configurations are not working, we plan to help submitters fix issues.

**Comment by gfursin** [comment]
We improved CM automation for Intel, Nvidia and Qualcomm and added to GUI: https://access.cknowledge.org/playground/?action=howtorun&bench_uid=39877bb63fb54725 . We can re-run most of them now.

**Comment by gfursin** [comment]
We now have relatively stable common CM interface to rerun above submissions and reproduce key results. I close this ticket - we will open a similar ticket for inference v4.0 after publication. Huge thanks to colleagues from Intel, Qualcomm and Nvidia for their help and suggestions!
