### ISSUE TITLE
Add license support in CM scripts and add "get cognata dataset" script

### ISSUE THREAD

**Issue by gfursin** [mlcommons/ck#1098]
Requested features:
* CM scripts must show licenses and let user accept or reject them (should be used for the private MLPerf inference models too)
* We should have variations for _full and _short datasets
* We should have variations to use different URLs

We can either add a key "must_accept_license":True in CM script meta or check if LICENSE.md file exists inside CM script or both.
Another point is that we may need different licenses per variation (i.e. _full dataset may need license while _short may be open to everyone) ... @arjunsuresh - let's discuss how to create this prototype for the next ABTF meeting. 

CC: @kaspermeck-arm

**Comment by arjunsuresh** [comment]
yes Grigori. I think we should show the license in the same way AndroidSDK tool is doing.

**Comment by gfursin** [comment]
Agree! We are now busy finalizing CM for MLPerf inference to release it next week - as soon as it's done, let's prototype it - I can help with that ...

**Comment by gfursin** [comment]
Should move to cm4mlops
