### ISSUE TITLE
CM failed to download torrent

### ISSUE THREAD

**Issue by willamloo3192** [mlcommons/ck#1113]
When i want to download dataset via torrent file using the CM tool, i was hit into this issue. Please help to resolve my issue. 

user@MyPC:~/ck$ cm run script "get validation dataset imagenet _2012 _full" --torrent=ILSVRC2012_img_val.tar-5d6d0df7ed81efd49ca99ea4737e0ae5e3a5f2e5.torrent

* cm run script "get validation dataset imagenet _2012 _full"

  * cm run script "detect os"
         ! cd /home/user/CM/repos/local/cache/62f369dc9bab4396
         ! call tmp-run.sh from /home/user/CM/repos/mlcommons@ck/cm-mlops/script/detect-os/run.sh
         ! call "postprocess" from /home/user/CM/repos/mlcommons@ck/cm-mlops/script/detect-os/customize.py

  * cm run script "download-and-extract file _extract _torrent"

    * cm run script "download torrent _torrent.ILSVRC2012_img_val.tar-5d6d0df7ed81efd49ca99ea4737e0ae5e3a5f2e5.torrent"

      * cm run script "get generic-sys-util _transmission"
           ! load /home/user/CM/repos/local/cache/1655eb2449d34b72/cm-cached-state.json
           ! cd /home/user/CM/repos/local/cache/5f5bdfd3f3f94aa0
           ! call tmp-run.sh from /home/user/CM/repos/mlcommons@ck/cm-mlops/script/download-torrent/run.sh
transmission-remote --download-dir /home/user/CM/repos/local/cache/5f5bdfd3f3f94aa0 -a ILSVRC2012_img_val.tar-5d6d0df7ed81efd49ca99ea4737e0ae5e3a5f2e5.torrent
Unexpected response: <!doctype html>
<html>
<head>
<meta http-equiv="refresh" content="0;url=https://7rx90003.ibosscloud.com/ibreports/ibp/bp.html?bu=http://localhost:9091/transmission/rpc/&bc=Failed+to+retrieve+requested+URL.&ip=10.221.109.19&er=ERR_CONNECT_FAIL&amp;user=%2a10.221.109.19&amp;fn=Restricted+Labs+%28port+918%29&amp;fp=8&amp;cn="/>
</head>
<body>
</body>
</html>

Unexpected response: <!doctype html>
<html>
<head>
<meta http-equiv="refresh" content="0;url=https://7rx90003.ibosscloud.com/ibreports/ibp/bp.html?bu=http://localhost:9091/transmission/rpc/&bc=Failed+to+retrieve+requested+URL.&ip=10.221.109.19&er=ERR_CONNECT_FAIL&amp;user=%2a10.221.109.19&amp;fn=Restricted+Labs+%28port+918%29&amp;fp=8&amp;cn="/>
</head>
<body>
</body>
</html>

CM error: Portable CM script failed (name = download-torrent, return code = 256)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Note that it may be a portability issue of a third-party tool or a native script
wrapped and unified by this automation recipe (CM script). In such case,
please report this issue with a full log at "https://github.com/mlcommons/ck".
The CM concept is to collaboratively fix such issues inside portable CM scripts
to make existing tools and native scripts more portable, interoperable
and deterministic. Thank you!!

**Comment by arjunsuresh** [comment]
Hi @willamloo3192 can you please do
```
cm run script "get validation dataset imagenet _2012 _full"
```

Currently we can download the full dataset without a torrent.

**Comment by willamloo3192** [comment]
Thanks, it works. Just that my domain have proxy. May I know how to bypass the proxy?

**Comment by gfursin** [comment]
@willamloo3192 

> Thanks, it works. Just that my domain have proxy. May I know how to bypass the proxy?

Thank you for your feedback. Just to clarify, would you like to have a possibility to pass PROXY_URL and PROXY_PORT to CM script to use it when downloading datasets (or anything else), or you want to have a way to provide an alternative URL to CM that somehow bypasses your proxy?

We can probably add support for both but just need to know what to do exactly ;) ...
Thanks!!!

**Comment by willamloo3192** [comment]
Hi @gfursin how to add the parameter to the script? Do we need to add --PROXY_URL="<url>" --PROXY_PORT=<port_num>? 
I keep hitting into the zenodo.org:443 on the verify certificate failed. 

Sample command line: cmr "run mlperf inference generate-run-cmds _submission" --quiet --submitter="MLCommons" --hw_name=default --model=bert-99 --implementation=reference --backend=pytorch --device=cuda --scenario=Offline --adr.compiler.tags=gcc  --target_qps=1 --category=edge --division=open --PROXY_URL="zenodo.org" --PROXY_PORT=443


Kindly need your help to resolve it

**Comment by gfursin** [comment]
Hi @willamloo3192 . 

Hmm, I believe that certificate issue on Zenodo is different from the Proxy issue. 
CM scripts call other CM sub-scripts to download artifacts. We can either pass global environment variables to all CM scripts using --env.KEY=value or to a specific dependency using --adr.{NAME OF DEPENDENCY}.env.KEY=value .

However, I need to understand which script fails on verify certificate. Can you please provide the complete log with very certificate failure? 

CM scripts do now support proxy to download artifacts yet but I can add such support if I understand how it works - I didn't use proxy for ages ... CM scripts can download artifacts via wget, curl, torrent and our internal Python download function. We need to agree on env variables to support PROXY and pass them to these tools. 

Maybe you can ping me on Discord and we can have a conf-call where you can show me what fails - it may be easier for me to understand the problem and extend CM ... 

Thanks!

**Comment by willamloo3192** [comment]
[cm compilation log.txt](https://github.com/mlcommons/ck/files/14422926/cm.compilation.log.txt)
Hi @gfursin 
I attached log file in this thread. I need your expertise to resolve the issue. Thanks a lot.

**Comment by gfursin** [comment]
> [cm compilation log.txt](https://github.com/mlcommons/ck/files/14422926/cm.compilation.log.txt) Hi @gfursin I attached log file in this thread. I need your expertise to resolve the issue. Thanks a lot.

Thank you! Oh, yes, that is what I was concerned about. Originally, we used our internal download routine but later we decided to move towards using wget as default since it fixes "certificate verify failed" ... Let me check it ...

**Comment by willamloo3192** [comment]
You're welcome, @gfursin 

Sure. To be honest, that's cause me the headache for several days. :)

**Comment by gfursin** [comment]
Sorry about that. I see that certificate checking was on by default in our internal download tool. Can you please rerun the same command line with `--env.CM_VERIFY_SSL=false`  added?

**Comment by willamloo3192** [comment]
@gfursin I had verified that the issue was resolved.

**Comment by gfursin** [comment]
Super! I will close this issue. You mentioned on Discord that loadgen fails - can you please open another ticket and we will check it! Thank you for your feedback!
