### ISSUE TITLE
cURL failed to download files

### ISSUE THREAD

**Issue by willamloo3192** [mlcommons/ck#1133]
**Command:** cm run script --tags=get,ml-model,sdxl,_fp16,_rclone -j 
**OS Version:** Ubuntu 22.04 with kernel 6.5.0
**CUDA Version:** 12.0
**Pytorch version:** 2.2.1

**Error Message:**
* cm run script "get ml-model sdxl _fp16 _rclone"

  * cm run script "download-and-extract _rclone _url.mlc-inference:mlcommons-inference-wg-public/stable_diffusion_fp16"

    * cm run script "download file _rclone _url.mlc-inference:mlcommons-inference-wg-public/stable_diffusion_fp16"

      * cm run script "detect os"
             ! cd /home/user/CM/repos/local/cache/b51cc1510fdc4701
             ! call tmp-run.sh from /home/user/CM/repos/mlcommons@ck/cm-mlops/script/detect-os/run.sh
             ! call "postprocess" from /home/user/CM/repos/mlcommons@ck/cm-mlops/script/detect-os/customize.py

      * cm run script "get rclone"
                 ! cd /home/user/CM/repos/local/cache/b7f224001d6d43a5
                 ! call tmp-run.sh from /home/user/CM/repos/mlcommons@ck/cm-mlops/script/get-rclone/run.sh
             ! cd /home/user/CM/repos/local/cache/b7f224001d6d43a5
             ! call tmp-run.sh from /home/user/CM/repos/mlcommons@ck/cm-mlops/script/get-rclone/install.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4734  100  4734    0     0   3960      0  0:00:01  0:00:01 --:--:--  3958
^C
CM error: Portable CM script failed (name = get-rclone, return code = 2)

**Question:**
Do we require passing PROXY in this command? If yes, what is the appropriate parameter shall we passed in?

**Comment by gfursin** [comment]
Thank you for reporting @willamloo3192 . There are multiple issues with the MLCommons cloud at the moment. I believe we had an alternative way to download models. Let me sync with @arjunsuresh today.

**Comment by arjunsuresh** [comment]
MLC downloads should be working fine now. Closing this issue for now. Please reopen if required.
