### ISSUE TITLE
Add global CM config

### ISSUE THREAD

**Issue by gfursin** [mlcommons/ck#1136]
Based on user feedback, we need to add global CM config (env vars, etc) for CM scripts in either .cm or CM directory ... 
It can be used to configure cloud instances (AWS/GCP) or CM functionality such as turning off SSL certificate check during downloads ...
Need to brainstorm a bit more ...

**Comment by gfursin** [comment]
We can use it to add rclone configs: See #1135 and #1134

**Comment by ctuning-admin** [comment]
Since I had to remove rclone private key from mlcommons@cm4mlops repo (I couldn't commit), we need to do it soon! I will check it when I have bandwidth ...
