### ISSUE TITLE
do not use sudo in "get rclone" on Linux

### ISSUE THREAD

**Issue by gfursin** [mlcommons/ck#1138]
While checking this issue #1133, I realized that while we download rclone binary on Windows, we use sudo apt on Linux and brew on MacOS. However, we can avoid that and also download rclone binary to CM cache on all Operating systems. I will try to fix that ...

**Comment by gfursin** [comment]
It's done now. We need to check on Mac though ... @arjunsuresh - do you think you can check if the new get rclone works on mac without the need for brew install. You can use Stable diffusion automation recipe for example:
```
cm rm cache -f
cmr "get ml-model sdxl _fp16"
```
By the way, I also added required disk space for SDXL for fp16 and fp32 ...

**Comment by arjunsuresh** [comment]
It works fine on macos. But I think the warning should not be printed when the script is already cached.

**Comment by gfursin** [comment]
Oh, yes, I agree! Let me check ;) !

**Comment by arjunsuresh** [comment]
Also with rclone we are not handling broken downloads in CM.

**Comment by gfursin** [comment]
I actually noticed that right now and it's also weird and that's I think is the issue reported in another ticket - rclone failed but CM cached it ... Do you know what happens - how can we fix it?

**Comment by arjunsuresh** [comment]
Probably we need to use a md5_file like we do [here](https://github.com/mlcommons/ck/blob/master/cm-mlops/script/prepare-training-data-bert/_cm.json#L62)

**Comment by gfursin** [comment]
Sure. But what is weird, is that I thought that if we cancel rclone, the entry should be marked with -tmp and we should still force to rerun rclone if exit !=0 ... That's what is weird. And we can check md5sum after if rclone was not cancelled but something went wrong ...

**Comment by gfursin** [comment]
> It works fine on macos. But I think the warning should not be printed when the script is already cached.

I believe I fixed it in the latest commit. It shouldn't print WARNINGS for cached entries ...

**Comment by gfursin** [comment]
Done.
