### ISSUE TITLE
ctuning/kilt-mlperf should be krai/kilt-mlperf?

### ISSUE THREAD

**Issue by psyhtest** [mlcommons/ck#1145]
The URL https://github.com/ctuning/kilt-mlperf is not public. It's referenced [here](https://github.com/mlcommons/ck/blob/0279936fd7f403cb31374732d0b49615ee4a06da/cm-mlops/script/get-kilt/_cm.json#L20).

**Comment by arjunsuresh** [comment]
Hi @psyhtest we were not using that script but rather directly using the repo URL [here](https://github.com/mlcommons/ck/blob/master/cm-mlops/script/reproduce-mlperf-inference-qualcomm/_cm.yaml#L36). And we were using a fork of krai/kilt-mlperf but mainly just for experimentation purpose - the main repo should also work fine for reproducing the results. I think this script is stale and we'll remove it. Thank you for pointing this out.

**Comment by arjunsuresh** [comment]
@gfursin This script is not needed right?

**Comment by gfursin** [comment]
No, it's not needed and we can remove it. It was for some old tests indeed.

**Comment by gfursin** [comment]
@arjunsuresh - I created a PR to remove this script since we do not use it - please merge it when you have time: https://github.com/mlcommons/ck/pull/1147 .
