### ISSUE TITLE
Simplifying README

### ISSUE THREAD

**Issue by shwetaj2820** [mlcommons/ck#1169]
https://github.com/mlcommons/ck/tree/master/cm-mlops/script/app-mlperf-inference-mlcommons-cpp#variation  

In this README, the given script (which is run from the command line) is not quite user friendly and needs some modification or further explanation. 

`cm run script --tags=app,mlcommons,mlperf,inference,cpp[,variations] [--input_flags]

cmr "app mlcommons mlperf inference cpp[ variations]" [--input_flags]`

**Comment by gfursin** [comment]
Thank you for your feedback @shwetaj2820 ! 

Agree! It was a while since we updated them. We plan to add a working solution with the --help flag first and then further explanations similar to
```
cm run script --tags=app,mlcommons,mlperf,inference,cpp --help
```
We will tell you when it's done!

**Comment by gfursin** [comment]
Done: https://github.com/mlcommons/ck/commit/8b8798135f0b76e7338186feb8c319973863ac9a . Will be available in master in the next PR. Thanks for your feedback again!
