### ISSUE TITLE
Why the results both on CPU and GPU are same?

### ISSUE THREAD

**Issue by KingICCrab** [mlcommons/ck#1180]
When I run
cmr "run mlperf inference generate-run-cmds _submission" --quiet --submitter="MLCommons" --hw_name=default --model=bert-99 --implementation=reference --backend=onnxruntime --device=cuda --scenario=Offline --adr.compiler.tags=gcc --target_qps=1 --category=edge --division=open
default-reference-gpu-onnxruntime-v1.17.1-default_config
+---------+----------+----------+--------+-----------------+---------------------------------+
| Model | Scenario | Accuracy | QPS | Latency (in ms) | Power Efficiency (in samples/J) |
+---------+----------+----------+--------+-----------------+---------------------------------+
| bert-99 | Offline | X () | 44.157 | - | |
+---------+----------+----------+--------+-----------------+---------------------------------+

when I run
cmr "run mlperf inference generate-run-cmds _submission" --quiet --submitter="MLCommons" --hw_name=default --model=bert-99 --implementation=reference --backend=onnxruntime --device=cpu --scenario=Offline --adr.compiler.tags=gcc --target_qps=1 --category=edge --division=open
default-reference-gpu-onnxruntime-v1.17.1-default_config
+---------+----------+----------+--------+-----------------+---------------------------------+
| Model | Scenario | Accuracy | QPS | Latency (in ms) | Power Efficiency (in samples/J) |
+---------+----------+----------+--------+-----------------+---------------------------------+
| bert-99 | Offline | X () | 44.157 | - | |
+---------+----------+----------+--------+-----------------+---------------------------------+
I change the "--device"
Why the results is same?

**Comment by gfursin** [comment]
There may be several potential issues with CUDA run - if CUDA is not installed properly or fails on your system, ONNX may revert to CPU. I didn't see that cases before but assume that this is the case. Also, we usually do not mix CPU and CUDA installation so you need to clean CM cache in between such runs:
```
cm rm cache -f
```
Maybe you can clean the cache and rerun above command with --device=cuda and submit the full log?
We may need to handle better such cases ... Thanks a lot again for your feedback - that helps us improve CM for everyone!

**Comment by arjunsuresh** [comment]
Please follow the [current docs](https://docs.mlcommons.org/inference/benchmarks/language/bert/) for running MLPerf inference. We currently use docker for Nvidia GPU runs by default as due to numerous dependency issues even if we specify `--device=cuda` the actual run might happen on CPUs.

**Comment by gfursin** [comment]
If there is still an issue , it should move to https://github.com/mlcommons/cm4mlops .
