### ISSUE TITLE
Print migration warning when using mlcommons@ck

### ISSUE THREAD

**Issue by gfursin** [mlcommons/ck#1215]
We need to print a warning to suggest to migrate to [mlcommons@cm4mlops](https://github.com/mlcommons/cm4mlops)

**Comment by arjunsuresh** [comment]
Hi @gfursin This change is very confusing to users and breaks all our previous readmes and any comments we had shared with users. If we cannot automatically alias mlcommons@ck to mlcommons@cm4mlops it might be better to not use the new repository.

**Comment by gfursin** [comment]
Thank you for your feedback @arjunsuresh . I will check how to deal with aliasing to see what will be less confusing to the users.

**Comment by arjunsuresh** [comment]
Thank you @gfursin "cm pull repo mlcommons@ck" is at too many places and we should make it work with the latest code. Also, with the new repo, the users are supposed to raise "issues" in the new one right?

**Comment by arjunsuresh** [comment]
Thank you @gfursin . We also have [this](https://github.com/mlcommons/cm-mlops/tree/main) repository.

My suggestion will be to keep `ck` repository for issues related to only 'CM core'.

**Comment by gfursin** [comment]
> Thank you @gfursin . We also have [this](https://github.com/mlcommons/cm-mlops/tree/main) repository.
> 
> My suggestion will be to keep `ck` repository for issues related to only 'CM core'.

Oh, thank you for reminding about this repo - I completely forgot about it ;) . I will ask MLCommons admins to delete it.

**Comment by gfursin** [comment]
Done.
