### ISSUE TITLE
Add universal check of env vars in cmind.utils

### ISSUE THREAD

**Issue by gfursin** [mlcommons/ck#1216]
We have lots of following code in CM scripts:

```python
    if str(env.get('CM_DOCKER_PUSH_IMAGE', '')).lower() in ['true', 'yes', 'on']:
```

I suggest to provide a `cmind.utils.is_env_true` and cmind.utils.is_env_false` to unify it ...
We will then need to add an extra check for min CM versions in such updated scripts: https://github.com/mlcommons/cm4mlops/issues/15

**Comment by ctuning-admin** [comment]
Done.
