### ISSUE TITLE
`convert_path` is not part of setuptools API and will be removed

### ISSUE THREAD

**Issue by abravalheri** [mlcommons/ck#1219]
Importing `setuptools.convert_path` has been deprecated for almost 2 years and is about to be removed.

https://github.com/mlcommons/ck/blob/baf3402a0de7b64d3c8289679360bc82beaa3d10/ck/setup.py#L25

https://github.com/mlcommons/ck/blob/baf3402a0de7b64d3c8289679360bc82beaa3d10/ck/incubator/cbench/setup.py#L11

https://github.com/mlcommons/ck/blob/baf3402a0de7b64d3c8289679360bc82beaa3d10/ck/incubator/cdatabase/setup.py#L6

In the past `setuptools` would import `convert_path` from one of its dependencies for internal use, but that is no longer true.

**Comment by gfursin** [comment]
Hi 

Thank you for noting that @abravalheri! 

The CK framework is archived and we do not update it unless requested by users, but this deprecation influence our new CM framework [here](https://github.com/mlcommons/ck/blob/master/cm/setup.py#L5).

Do you know if there is an alternative from distutils? Should I do something like [this code](https://github.com/mlcommons/ck/blob/master/cm/setup.py#L7) to import it (while keeping backward compatibility for older systems with setuptools)? 

Thank you!

**Comment by abravalheri** [comment]
> Do you know if there is an alternative from distutils? Should I do something like [this code](https://github.com/mlcommons/ck/blob/master/cm/setup.py#L7) to import it (while keeping backward compatibility for older systems with setuptools)?

Hi @gfursin, I find that `convert_path` is usually not essential for implementing the common functionality.

This is the description of the function:

>  ```python
>     """Return 'pathname' as a name that will work on the native filesystem,
>     i.e. split it on '/' and put it back together again using the current
>     directory separator.  Needed because filenames in the setup script are
>     always supplied in Unix style, and have to be converted to the local
>     convention before we can actually use them in the filesystem.  Raises
>     ValueError on non-Unix-ish systems if 'pathname' either starts or
>     ends with a slash.
>     """
>  ```

But most of the Python functions nowadays allow you to use `/` for paths even on windows...

Other than that, the function also raises an error if the path is absolute or if it ends in `/`, but that is easily implementable with `os.path.isabs` and `str.rstrip` if needed... Finally, if normalisation is needed you can go with `os.path.normpath`.

**Comment by abravalheri** [comment]
I see that in this particular `setup.py` what is being used is something like:

```python
long_description=open(convert_path('./README.md'),
                          encoding="utf-8").read(),
```

which probably will work just fine if you replace
`convert_path('./README.md') => "README.md"`

**Comment by gfursin** [comment]
Cool! Thank you for the update. Let me check it this week!

**Comment by gfursin** [comment]
I removed convert_path from the CM framework. 

Are you using CK framework? If not, I prefer not to touch it until it really fails in the future ;) ...

**Comment by abravalheri** [comment]
Hi @gfursin, thank you for taking a look on this.

No, I am not working with CK. I am working on removing deprecated parts from setuptools.

**Comment by gfursin** [comment]
Sure. Thanks for noting the issue! Then the CM project should be fine but we keep CK archived for now. I will close this issue!
