### ISSUE TITLE
Warning Encountered During pip install cmind on Ubuntu via WSL

### ISSUE THREAD

**Issue by sahilavaran** [mlcommons/ck#1232]
Hi [Repository/Project Team],

I encountered a warning while installing a Python package using pip install cmind on Ubuntu through Windows Subsystem for Linux (WSL). The solution was to update the PATH variable to resolve the issue. I've attached an image that captures the warning message for your reference.

Could you help me understand why this might have occurred and suggest any best practices for maintaining the correct environment variables? Any insights you provide would be greatly appreciated.

Thank you for your assistance.

Best regards,
sahil
![IMG-20240426-WA0021](https://github.com/mlcommons/ck/assets/139779393/c358b574-d907-465b-830f-186b6d9d9610)

**Comment by gfursin** [comment]
Hi @sahilavaran . 

Normally, when you install some python package (not only CM) that uses binaries as a command line, they are created in $HOME/.local/bin . In such case, pip should update your `.profile` file  and add $HOME/.local/bin to your PATH there. 

Can you please log out from WSL and log in again? You should normally be able to use CM ... 

Can you please also check your `.profile` file and see if you have $HOME/.local/bin path there?

I use UBUNTU via WSL and have the following lines in my `profile` (automatically added):

```
# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi
```

**Comment by sahilavaran** [comment]
Hi @gfursin 

Sure, I'll log out and back into WSL and check if the .profile file has $HOME/.local/bin in the PATH.

**Comment by gfursin** [comment]
Cool! We documented it [here](https://github.com/mlcommons/ck/blob/master/docs/installation.md) but it is in the middle and may not be visible to users. Do you think there should be a better way to warn users about this feature?

**Comment by arjunsuresh** [comment]
Closing this for now. Please reopen if required.
