### ISSUE TITLE
Support ssh URLs in cm pull repo

### ISSUE THREAD

**Issue by arjunsuresh** [mlcommons/ck#1253]
Currently only 'https' is supported in CM pull repo and this causes problems to users using `ssh` access like reported [here](https://discord.com/channels/864995525526290502/1167509983810814042/1243234719022186646)

**Comment by gfursin** [comment]
Not sure what you mean. I believe we can pass --url to `cm pull repo` to specify any protocol? I think this should work:
```
cm pull repo --url=git+ssh://github.com/mlcommons/cm4abtf --checkout=dev
```

**Comment by arjunsuresh** [comment]
If we are following the github URLs, we get the SSH URL in this form: git@github.com:mlcommons/ck.git which currently does not work with `cm pull repo`

I think we should support that and when users use "mlcommons@ck" there should be a parameter like `--protocol=ssh` or simply `--ssh` to automatically use SSH. 

Also `checkout` is currently broken (won't pull changes on a retry) similar to `--branch` issue reported [here](https://github.com/mlcommons/ck/issues/1244)

```
arjun@arjun-spr:~/CM/repos/mlcommons@cm4abtf$ cm pull repo --url=git+ssh://github.com/mlcommons/cm4abtf --checkout=dev
=======================================================
Alias:    mlcommons@cm4abtf
URL:      git+ssh://github.com/mlcommons/cm4abtf
Checkout: dev

Local path: /home/arjun/CM/repos/mlcommons@cm4abtf

git pull

There is no tracking information for the current branch.
Please specify which branch you want to rebase against.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> dev


git checkout dev

Already on 'dev'

CM alias for this repository: mlcommons@cm4abtf

```

**Comment by gfursin** [comment]
Ok. I see. Sure, it will be useful to add such support.

**Comment by anandhu-eng** [comment]
Tested PR https://github.com/mlcommons/ck/pull/1346, its working fine. Closing the issue.
