### ISSUE TITLE
prototype "cm init" to check some system deps (git, wget) and pull cm4mlops repo

### ISSUE THREAD

**Issue by gfursin** [mlcommons/ck#1279]

**Comment by gfursin** [comment]
I implemented this functionality. @arjunsuresh and @anandhu-eng - can you please check that it works on your side? We can then discuss how to update the docs to keep the installation clean ... Thanks!

**Comment by arjunsuresh** [comment]
Hi @gfursin I added `cm init` to [this github action](https://github.com/mlcommons/ck/actions/runs/10902026986/job/30253017157?pr=1285). It works fine on Ubuntu but fails on Windows. Is this expected?

**Comment by gfursin** [comment]
Hmm, thank you for noting - let me check.

**Comment by gfursin** [comment]
Oh, yes, I see the problem. We should not check wget.exe in "cm init" on Windows since it is added/used via cm scripts ... At this moment "cm init" fails on Windows because wget is not available ;) ...

**Comment by gfursin** [comment]
I have tested `cm init` in various projects - it seems to be working fine and I can capture and process installation errors via CM interface.

@arjunsuresh - may I ask you to update the docs at https://docs.mlcommons.org/inference/install/#__tabbed_1_1 to use `pip install cmind && cm init` as default, please? 

In the future, we may be extending `cm init` with other repositories that are not necessarily related to cm4mlops ...

Thanks a lot!

**Comment by arjunsuresh** [comment]
Hi @gfursin For MLPerf run support especially for new users the current `cm4mlops` package is working really well and so far we have had no issues raised regarding this. We also have the `cm init` option as an alternative for those doing development work. I don't think we should change the default setting and invite more support queries. 

Also, can you please add MLCommons to the `cmind` pypi package owner list? Initially we had to create `cm4mlops` package when we were not able to do a critical `cmind` release when you were offline.

**Comment by gfursin** [comment]
Sure, let's keep two methods - I have MLPerf users that prefer original installation to have a control over which CM repositories they initialize and use - they can now choose whatever is better for them.
