### ISSUE TITLE
Where are the sources of CK/CM/CM4MLOps docs hosted

### ISSUE THREAD

**Issue by gfursin** [mlcommons/ck#1299]
Hi @arjunsuresh,

Can you please help me find the current sources of CK/CM/CM4MLOps docs hosted? 

* https://docs.mlcommons.org/inference/
* https://docs.mlcommons.org/ck/
* https://docs.mlcommons.org/inference/benchmarks/text_to_image/reproducibility/scc24

Also what is the GitHub action to generate them?

Thanks a lot!

**Comment by arjunsuresh** [comment]
Hi @gfursin they are in the `docs` folder inside the respective github repositories.

**Comment by gfursin** [comment]
Cool! Thanks a lot @arjunsuresh !
