### ISSUE TITLE
[CK legacy -> CK2] adding --check-license flag to the "ck pull repo" command

### ISSUE THREAD

**Issue by gfursin** [mlcommons/ck#134]
We got an interesting idea to add a --check-license flag to the "ck pull repo" command to check all licenses and copyrights of all pulled repositories. Need to brainstorm it a bit further ...

The idea is to make sure that all components of a given workflow have compatible licenses ...

**Comment by psyhtest** [comment]
Nearly all CK wrappers today have the standard CK license. I'd say it is the license of the wrapped components that may present more of a problem.

**Comment by gfursin** [comment]
That's true! We can actually scan all modules from pulled repos and check the headers for the license - it shouldn't be very difficult to do ...

**Comment by psyhtest** [comment]
A component's license can be part of the metadata in a standardised format? For example, we can use ids like https://opensource.org/licenses/BSD-3-Clause

**Comment by gfursin** [comment]
For now, most of the CK2 (CM) repos are shared under Apache 2.0 license so there is no problem. Whenever we encounter this issue in the new CK2 framework, let's reopen this ticket and add it there. Thanks!
