### ISSUE TITLE
[CK legacy -> CK2] Automatically test CK releases using Dockers with different ML/SW/HW stacks

### ISSUE THREAD

**Issue by gfursin** [mlcommons/ck#163]
I would like to substitute travis/appveyour tests with more rigorous testing of CK and all related components using different ML/SW/HW stacks (including MLPerf benchmark). 

As a base, we can use already existing Docker images for CK:
* https://github.com/octoml/mlops/tree/main/docker
* https://github.com/ctuning/ck-mlops/tree/main/docker

We can later connect these Docker images with GitHub actions.

**Comment by gfursin** [comment]
Prepared the first set of containers to test CK with different Ubuntu and Python versions using old and new MLPerf workflows: https://github.com/ctuning/ck-mlops/tree/main/docker/test-ck . We can use it as a starting point. Later we should generate such Docker images automatically.

**Comment by gfursin** [comment]
Tested on the latest CK release v2.5.8.

**Comment by gfursin** [comment]
Found some notes about GitHub actions for Python: https://docs.github.com/en/actions/guides/building-and-testing-python

**Comment by gfursin** [comment]
We plan to implement it in the CK2

**Comment by arjunsuresh** [comment]
This is now implemented in CM. Can we close this issue?

**Comment by gfursin** [comment]
Sure. Done.
