### ISSUE TITLE
[CK legacy][MacOS][TVM] Framework installation (TVM)

### ISSUE THREAD

**Issue by KJlaccHoeUM9l** [mlcommons/ck#164]
1) When building TVM on MacOS, dynamic libraries have a `.dylib` extension, but for checking `end_full_path_universal` in the `CK / local / venv / mlperf-inference / CK / ck-mlops / package / compiler-tvm / .cm / meta.json` file the `.so` extension, because of this, the assembled framework was not registered in the UID.
2) Also in the dependencies for TVM, LLVM was specified, which was downloaded and built from the source code. When working with this compiler, there were problems, therefore, to solve them, the dependency on LLVM from the source code was removed from the corresponding file so that the system LLVM that was installed on the system was used.
`git diff` for these changes:

```
diff --git a/package/compiler-tvm/.cm/meta.json b/package/compiler-tvm/.cm/meta.json
index 222ef507..624c89cd 100644
--- a/package/compiler-tvm/.cm/meta.json
+++ b/package/compiler-tvm/.cm/meta.json
@@ -38,16 +38,16 @@
       "name": "C++ compiler",
       "sort": 10,
       "tags": "compiler,lang-cpp"
-    },
-    "lib-llvm": {
-      "add_to_path": "no",
-      "local": "no",
-      "name": "LLVM libraries",
-      "sort": 90,
-      "tags": "llvm,source,v8"
     }
+    // "lib-llvm": {
+    //   "add_to_path": "no",
+    //   "local": "no",
+    //   "name": "LLVM libraries",
+    //   "sort": 90,
+    //   "tags": "llvm,source"
+    // }
:...skipping...
diff --git a/package/compiler-tvm/.cm/meta.json b/package/compiler-tvm/.cm/meta.json
index 222ef507..624c89cd 100644
--- a/package/compiler-tvm/.cm/meta.json
+++ b/package/compiler-tvm/.cm/meta.json
@@ -38,16 +38,16 @@
       "name": "C++ compiler",
       "sort": 10,
       "tags": "compiler,lang-cpp"
-    },
-    "lib-llvm": {
-      "add_to_path": "no",
-      "local": "no",
-      "name": "LLVM libraries",
-      "sort": 90,
-      "tags": "llvm,source,v8"
     }
+    // "lib-llvm": {
+    //   "add_to_path": "no",
+    //   "local": "no",
+    //   "name": "LLVM libraries",
+    //   "sort": 90,
+    //   "tags": "llvm,source"
+    // }
   },
-  "end_full_path_universal": "tvm/build/libtvm.so",
+  "end_full_path_universal": "tvm/build/libtvm.dylib",
   "only_for_host_os_tags": [
     "linux"
   ],
```

**Comment by gfursin** [comment]
Thank you for the report @KJlaccHoeUM9l ! Let me check it, please!

**Comment by gfursin** [comment]
Hi! I believe I fixed the TVM package meta to support Linux and MacOS at the same time: https://github.com/octoml/mlops/blob/main/package/compiler-tvm-from-src/.cm/meta.json

By the way, I've realized that you were looking at the outdated LLVM and TVM packages. The updated ones are:
* https://github.com/octoml/mlops/tree/main/package/compiler-tvm-from-src
* https://github.com/octoml/mlops/tree/main/package/compiler-llvm-from-src

Another note: when installing packages via CK, we set up many related ENV variables that are used by other packages and program workflows. Removing this dependency from meta.json may work but you need to set up lots of ENV vars manually.

Instead, you should use "ck detect soft" automation that plugs in already installed software, models or datasets into CK. Hence, you need to do the following for LLVM before installing TVM package:
```
ck detect soft:compiler.llvm
```

This CK automation will search for all installed LLVM instances on your machine (in most common places).

Alternatively, you can specify or narrow down the search via 
```
ck detect soft:compiler.llvm --search_dirs={directory with LLVM}
```

Finally, you can specify the full path to clang as follows:
```
ck detect soft:compiler.llvm --full_path={FULL PATH to clang}
```

Please tell me if works!
Thanks a lot for your feedback and for supporting this community project!

**Comment by gfursin** [comment]
I updated the TVM-MLPerf installation docs to describe how to detect or install cmake, llvm and tvm: https://github.com/ctuning/ck/blob/master/docs/mlperf-automation/setup/framework-tvm.md

**Comment by gfursin** [comment]
We have a new package to install TVM in CM. We should check it. I close this ticket.
