### ISSUE TITLE
[CK legacy][MacOS][PyTorch] Framework installation (PyTorch)

### ISSUE THREAD

**Issue by KJlaccHoeUM9l** [mlcommons/ck#165]
When using `Python3.9`, the minimum `PyTorch==1.7.1` version, but in the config in the `CK / local / venv / mlperf-inference / CK / ck-mlops / package / lib-python-torch / .cm / meta.json` file the maximum the version is `1.6.0`, which causes an error when installing PyTorch using the following command: `ck install package --tags = lib, python-package, pytorch`. To solve this problem, the required version was added to the config.
`git diff`:

```
diff --git a/package/lib-python-torch/.cm/meta.json b/package/lib-python-torch/.cm/meta.json
index 5a990e86..ffea02b0 100644
--- a/package/lib-python-torch/.cm/meta.json
+++ b/package/lib-python-torch/.cm/meta.json
@@ -15,7 +15,8 @@
       "1.4.0",
       "1.5.0",
       "1.5.1",
-      "1.6.0"
+      "1.6.0",
+      "1.9.0"
     ]
   },
   "deps": {
```

**Comment by gfursin** [comment]
Thank you for the report @KJlaccHoeUM9l! I added variations for Torch and TorchVision packages:
* https://github.com/ctuning/ck-mlops/blob/bb5de25fa237058f2c833e9ec21add44b83b800d/package/lib-python-torch/.cm/meta.json#L38
* https://github.com/ctuning/ck-mlops/blob/bb5de25fa237058f2c833e9ec21add44b83b800d/package/lib-python-torchvision/.cm/meta.json#L45

Can you please check if it works?
You can update your installed repos as follows:
```
ck pull all
```
and then try to run the same command:
```
ck install package --tags = lib, python-package, pytorch
```

You should now see the new versions available. Thank you again!

**Comment by gfursin** [comment]
This ticket is outdated. We will use CK2 framework instead.
