### ISSUE TITLE
[MacOS][MLPerf] Test Accuracy

### ISSUE THREAD

**Issue by KJlaccHoeUM9l** [mlcommons/ck#166]
When running this test with the following command:
```
ck run program:mlperf-inference-bench-image-classification-tvm-onnx-cpu \
        --cmd_key=accuracy-offline
```
there were the following problems:
1) Building loadgen using clang, which was downloaded using CK, failed, it did not see the standard `.h` files. This problem was solved by using the system clang, for this it was necessary to define the following system variables:
```
export CPLUS_INCLUDE_PATH=/usr/local/opt/llvm/include/c++/v1:/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include
export LIBRARY_PATH=$LIBRARY_PATH:/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib
```
2) After that, the assembly still ended with an error, this was due to the fact that the compiler did not find the overloaded `operator<<` for `std::vector<unsigned long>`, this is due to the fact that the `int64_t` type was used for overloading, but on `MacOS` it expands to `unsigned long long`, another overload was written to solve this problem using the `size_t` type.
`git diff`:
```
diff --git a/loadgen/logging.cc b/loadgen/logging.cc
index e1846f0..61f9c2d 100644
--- a/loadgen/logging.cc
+++ b/loadgen/logging.cc
@@ -138,6 +138,16 @@ const std::string ArgValueTransform(const std::vector<uint64_t>& value) {
   return s;
 }
+const std::string ArgValueTransform(const std::vector<size_t>& value) {
+  std::string s("[");
+  for (auto i : value) {
+    s += std::to_string(i) + ",";
+  }
+  s.resize(s.size() - 1);
+  s += "]";
+  return s;
+}
+
 const std::string ArgValueTransform(
     const std::map<std::string, std::string>& value) {
   std::string s("{");
diff --git a/loadgen/logging.h b/loadgen/logging.h
index f89b18a..e090908 100644
--- a/loadgen/logging.h
+++ b/loadgen/logging.h
@@ -86,6 +86,7 @@ const std::string ArgValueTransform(const std::string& value);
 const std::string ArgValueTransform(const char* value);
 /// \brief Prints a list of int in JSON format.
 const std::string ArgValueTransform(const std::vector<uint64_t>& value);
+const std::string ArgValueTransform(const std::vector<size_t>& value);
 /// \brief Prints a dict in JSON format.
 const std::string ArgValueTransform(
     const std::map<std::string, std::string>& value);
```
3) Dependency on `pycocotools` for `Image Classification` task. This package of functions is needed for the `Object Detection` task, but at the same time it is installed for the accuracy test on the `ImageNet` dataset. This package is built from source code, so there were also problems with it because clang, which pulled up CK, does not see the standard `.h` files.

**Comment by gfursin** [comment]
This problem relates to the official MLCommons inference code - need to check how to fix it - maybe we can submit a patch to MLCommons directly ...

**Comment by gfursin** [comment]
The latest version of the CK prototype is stable and successfully used by different companies and organizations to automate MLPerf inference submissions. That is why we have decided not to touch it anymore expect bug fixes in the CK kernel and existing [MLOps components](https://github.com/mlcommons/ck-mlops). Instead, we are developing a new CK2 framework based on user feedback.

I close this issue.
