### ISSUE TITLE
Object Detection Workflow has error

### ISSUE THREAD

**Issue by slahiruk** [mlcommons/ck#168]
https://github.com/ctuning/ck/blob/master/docs/mlperf-automation/reproduce/ck-object-detection-rpi4-tflite.md <- I was trying to follow this and obtained the following error
```
CK error: [cmdgen] build_map[library] is missing both 'tflite-v2.4.1-ruy' and '###' values! 
```

**Comment by gfursin** [comment]
Thank you very much, @slahiruk! Will need to check it when I have time!

**Comment by gfursin** [comment]
Hi @slahiruk . I fixed the workflow and it should work now for tflite-v2.4.1 and tflite-2.4.2 . Can you please check if it works?

I also updated the docs to include native CK program workflows that can be connected with our new end-to-end MLPerf submission system: https://github.com/octoml/mlops/tree/main/module/bench.mlperf.inference .

Thanks again for supporting this community project!

**Comment by gfursin** [comment]
Don't forget to pull updated repos ;) :
```
ck pull all
```

**Comment by slahiruk** [comment]
Hi @gfursin  I have confirmed that these updates are working for the raspberry pi 4!

**Comment by gfursin** [comment]
Great! Thank you for the update! I close this issue!
