### ISSUE TITLE
most close platform was not found in CK!

### ISSUE THREAD

**Issue by filven** [mlcommons/ck#181]
I installed CK in a Yocto build inspired from https://github.com/dividiti/ck-caffe/wiki/Installation_Linux#yocto-installing-ck.
The process was succesful but then when I was trying to run ck commands I kept getting the error `most close platform was not found in CK!`, what does this output mean and can I do something about it?

Here are some examples on how I produced that error.
```
$ ck install package --tags=mlperf,object-detection,model,tf,ssd-mobilenet,quantized
sh: getconf: not found
CK error: [package] most close platform was not found in CK!

$ ck detect platform.os --platform_init_uoa=generic-linux-dummy
sh: getconf: not found
CK error: [platform.os] most close platform was not found in CK!
```

Thanks!

**Comment by gfursin** [comment]
I have a feeling that there is a problem with your Python installation.

Which Python version are you using?

What is the output of the following Python commands:
```
    import os
    import platform
    import struct

    print (str(8 * struct.calcsize("P")))
    print (platform.system())
```

Thank you!

**Comment by filven** [comment]
Hello, thank you for getting back to me. I solved the issue. I added some configurations on my Yocto build:
 ```
...
PACKAGE_CLASSES ?= "package_deb"
CORE_IMAGE_EXTRA_INSTALL="dpkg"
EXTRA_IMAGE_FEATURES = "tools-sdk tools-debug"
```
Not sure which one did the trick and I also set the system's date-time. It takes time to test each setting. Now your above Python instructions work and the above commands. Should that be of interest, I can try to find out at my earliest convenience.

**Comment by gfursin** [comment]
Glad that it works now! I have added your notes [here](https://github.com/mlcommons/ck/blob/master/docs/mlperf-automation/platform/x8664-yocto.md) to help the community find this solution for Yocto! 
No need to run the code above - I believe it will work now since your configuration probably fixed the getconf issue.
Don't hesitate to get in touch if you encounter other problems and thank you for sharing the solution!
