### ISSUE TITLE
CK v2.5.9

### ISSUE THREAD

**Issue by psyhtest** [mlcommons/ck#183]
Hi @gfursin, is there a timeline for the next CK release to include e.g. https://github.com/mlcommons/ck/pull/180?

**Comment by gfursin** [comment]
Hi @psyhtest. 
Thank you for the reminder. 
We thought to release the new CK version this weekend (we will have a CK tutorial at TVMCon this week and didn't want to do changes before that).
Are there any other updates you may need to push to the new CK version? Please tell me before the release ...
Thanks!!!

**Comment by psyhtest** [comment]
Thanks @gfursin ! I think that change should be sufficient to unblock us using CK v2.x for MLPerf Inference v2.0...

**Comment by gfursin** [comment]
Hi all. We need a few extra tests for our new MLPerf workflows for BERT and DLRM in https://github.com/mlcommons/ck-mlops .
If it doesn't influence your projects, we will release the new framework immediately after vacations (around 3rd of January).
Thank you for your patience!

**Comment by gfursin** [comment]
Happy New Year!
We have released the version 2.6.0. 
Please tell me if it works on your workflows as expected. We can close this ticket after that.
Thanks!

**Comment by arjunsuresh** [comment]
Thank you @gfursin. ck==2.6.0 is working as expected. Happy New Year 🥳

**Comment by gfursin** [comment]
Great! Thank you @arjunsuresh for confirming! I close this issue.
