### ISSUE TITLE
json.loads() should be called without encoding="..." in python3.x , crashes on python3.9 otherwise

### ISSUE THREAD

**Issue by ens-lg4** [mlcommons/ck#184]
There is currently a bug in CK's kernel (both v1.17 branch and higher branches) which prevents the users from running some CK commands in Python 3.9 and later.

The minimalistic example that still works in Python3.8 and breaks in Python3.9 is:
```
ck version "@@@{'meta':{}}"
```

I have traced it to the call to `d=json.loads(s, encoding='utf8')` inside `convert_json_str_to_dict()` function.  It should be wrapped in a version check:
```
       if sys.version_info[0]>2:
           d=json.loads(s)
       else:
           d=json.loads(s, encoding='utf8')
```

**Comment by gfursin** [comment]
I have fixed this problem and committed: https://github.com/mlcommons/ck/commit/a192c5f70dd296a9262464c2ef7ceb169fb2e1cf

Should I release V2.6.1 (it seems to be a critical issue) or you have some other suggestions/updates/patches?

Thanks a lot for your feedback!

**Comment by psyhtest** [comment]
Thanks @gfursin, that would be great!

**Comment by gfursin** [comment]
Done. V2.6.1 release should be available at PYPI shortly. Thanks again for your feedback.
