### ISSUE TITLE
Adding support for AOCC compiler

### ISSUE THREAD

**Issue by arjunsuresh** [mlcommons/ck#185]
I was trying to add AOCC compiler as a soft entry in CK. But while using the detected AOCC compiler to run ck program it complains of "No compiler description" found and after turning off the check, the program works. Is there a way to provide compiler description of AOCC so that we can properly use it for CK programs?

**Comment by gfursin** [comment]
Thank you for your note, @arjunsuresh . I didn't work with AOCC before and need some more info.
Did you add "soft" entry to detect AOCC already? If yes, can you share it with me, please? It will help me associate tags with the compiler description entry.
If not, can you please tell me where I can download AOCC - I can play with it to check how to set it up properly with CK.
Thanks!

**Comment by arjunsuresh** [comment]
Thanks a lot @gfursin. Yes I added the soft entry for AOCC by slightly modifying that of compiler.llvm, mainly for version detection which is added below. AOCC can be downloaded from here: [AOCC Download](https://developer.amd.com/amd-aocc/#downloads). 

```
{
  "auto_detect": "yes",
  "customize": {
    "add_only_with_version": "yes",
    "build_dir_name": "aocc",
    "can_strip_dynamic_lib": "yes",
    "check_that_exists": "yes",
    "ck_version": 10,
    "env_prefix": "CK_ENV_COMPILER_AOCC",
    "languages": [
      "C",
      "CPP",
      "F77",
      "F90",
      "F95"
    ],
    "limit_recursion_dir_search": {
      "linux": 4
    },
    "only_for_target_os_tags": [
      "linux"
    ],
    "skip_soft_file_is_asked": "yes",
    "soft_file": {
      "linux": "setenv_AOCC.sh"
    },
    "soft_file_as_env": "CK_CC",
    "soft_file_from_host_os": "yes",
    "soft_file_not_tool": "yes",
    "soft_path_example": {
      "linux": "/opt/AMD/setenv_AOCC.sh"
    },
    "soft_version_cmd": {
      "linux": "--version |cut -d':' -f2|cut -d'-'  -f1 | cut -d '_' -f2 | head -n 1 > $#filename#$ 2>&1",
      "win": " > $#filename#$ 2>&1"
    }
  },
  "env": {},
  "soft_name": "AOCC compiler",
  "tags": [
    "compiler",
    "aocc",
    "fortran",
    "lang-c",
    "lang-cpp",
    "lang-f77",
    "lang-f90",
    "lang-f95"
  ]
}
```

**Comment by gfursin** [comment]
The latest version of the CK prototype is stable and successfully used by different companies and organizations to automate MLPerf inference submissions. That is why we have decided not to touch it anymore expect bug fixes in the CK kernel and existing [MLOps components](https://github.com/mlcommons/ck-mlops). Instead, we are developing a new CK2 framework based on user feedback.

I close this issue.
