### ISSUE TITLE
ck install tflite failed on ARM64 platform

### ISSUE THREAD

**Issue by tsrjzq** [mlcommons/ck#187]
Hi,
I'm trying to install tflite on arm64 platform with ck, but failed. one of patch file not found. I try to download it(https://bitbucket.org/eigen/eigen/get/9f48e814419e.tar.gz) manually, it doesn't exist. The full log is as below.

ubuntu@VM-0-4-ubuntu:~$ ck install package --tags=lib,tflite,v1.13

  Package found: lib-tflite-1.13.1-src-static (bbde49998ab62431)

  -----------------------------------
  Resolving software dependencies ...

*** Dependency 1 = compiler (C++ compiler):

    Resolved. CK environment UID = 167a7356bb79117b (detected version 10.0.0)
  -----------------------------------

Searching if CK environment for this package already exists using:
  * Tags: compiled-by-llvm,compiled-by-llvm-10.0.0,lib,tensorflow,lite,tflite,tensorflow-lite,tensorflow-static,vsrc,vstatic,v1.13.1,v1.13,v1,channel-stable,host-os-linux-64,target-os-linux-64,64bits
  * Dependency: compiler=167a7356bb79117b

CK environment not found for this package ...

*** Installation path used: /home/ubuntu/CK-TOOLS/lib-tflite-src-static-1.13.1-llvm-10.0.0-linux-64

  -----------------------------------
  Resolving software dependencies ...

*** Dependency 1 = compiler (C++ compiler):

    Resolved. CK environment UID = 167a7356bb79117b (detected version 10.0.0)
  -----------------------------------

Installing to /home/ubuntu/CK-TOOLS/lib-tflite-src-static-1.13.1-llvm-10.0.0-linux-64

--------------------------------
Cloning package https://github.com/tensorflow/tensorflow ...

Cloning into 'src'...
remote: Enumerating objects: 1298480, done.
remote: Counting objects: 100% (102/102), done.
remote: Compressing objects: 100% (61/61), done.
remote: Total 1298480 (delta 42), reused 97 (delta 41), pack-reused 1298378
Receiving objects: 100% (1298480/1298480), 828.72 MiB | 17.34 MiB/s, done.
Resolving deltas: 100% (1054695/1054695), done.
Updating files: 100% (25509/25509), done.
--------------------------------
Checking out branch v1.13.1 ...

Updating files: 100% (26862/26862), done.
Note: switching to 'v1.13.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 6612da89516 Merge pull request #26101 from gunan/r1.13
--------------------------------
Preparing sources ...

[Patcher] Patching of the original code enabled
[Patcher] Original patch patterns: ${ORIGINAL_PACKAGE_DIR}/patch.${CK_TARGET_OS_ID}/*
[Patcher] Resolved patch filenames: /home/ubuntu/CK/ck-tensorflow/package/lib-tflite-1.13.1-src-static/patch.linux/Makefile.patch
[Patcher] Applying patch /home/ubuntu/CK/ck-tensorflow/package/lib-tflite-1.13.1-src-static/patch.linux/Makefile.patch
patching file tensorflow/lite/tools/make/Makefile
--------------------------------
Download dependencies ...

downloading https://bitbucket.org/eigen/eigen/get/9f48e814419e.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   CK detected a PROBLEM in the third-party CK package:

   CK package:           lib-tflite-1.13.1-src-static
   Native package URL:   https://github.com/tensorflow/tensorflow
   Git checkout:         v1.13.1
   CK repo:              ck-tensorflow
   CK repo URL:          https://github.com/krai/ck-tensorflow
   CK package URL:       https://github.com/krai/ck-tensorflow/tree/master/package/lib-tflite-1.13.1-src-static
   Issues URL:           https://github.com/krai/ck-tensorflow/issues

   CK stable package URL: https://cKnowledge.io/c/package/lib-tflite-1.13.1-src-static

   Please, check that there is no discussion about this issue at https://cKnowledge.io/c/package/lib-tflite-1.13.1-src-static

   Please, submit the original comand line and the *full* log to:
     * https://github.com/mlcommons/ck/issues
     * https://github.com/mlcommons/ck-mlops/issues
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

CK error: [package] package installation failed!

**Comment by gfursin** [comment]
Thank you for your feedback. 

It seems that you are using a third-party repository to install tflite. I suggest you to check the guidelines to install TFLite for ARM64 via CK using MLCommons CK repositories: https://github.com/mlcommons/ck/blob/master/docs/mlperf-automation/reproduce/ck-image-classification-rpi4-tflite.md ...

I remember that I have fixed this problem with EIGEN library in the [mlcommons@ck-mlops repo](https://github.com/mlcommons/ck-mlops/blob/main/package/lib-tflite-1.13.1-src-static). 

However, if it is also failing, I will need to check it further ...

Thank you and have a nice weekend!

**Comment by tsrjzq** [comment]
Thank you gfursin, I modified download_dependencies.sh in tensorflow and change EIGEN to other download address, now it is OK now.
