### ISSUE TITLE
[CK2/CM components] unifying tags

### ISSUE THREAD

**Issue by gfursin** [mlcommons/ck#202]
We want to unify the usage of tags and reserve specific prefixes for our universal CM artifacts related to version, variation or no tags. I.e. something like:
"v-", "no-", etc ...

It was suggested during [today's conf-call](https://github.com/mlcommons/ck/blob/master/ck2/meetings/notes-20220406.md).

**Comment by arjunsuresh** [comment]
Sometimes we may use tags like "no-nms" for a model. So, probably "n-" can be the reserved prefix, instead of "no-". 
 
In CK, tag names are appended using "-" for creating the install directory name. So, "-" appearing inside tags used to create confusion. Currently not sure how we can fix this -- append tags using "_" and not allowing "_" in tag names is a possible fix.

**Comment by gfursin** [comment]
> Sometimes we may use tags like "no-nms" for a model. So, probably "n-" can be the reserved prefix, instead of "no-".
> 
> In CK, tag names are appended using "-" for creating the install directory name. So, "-" appearing inside tags used to create confusion. Currently not sure how we can fix this -- append tags using "_" and not allowing "_" in tag names is a possible fix.

Very interesting! Thank you for your feedback, Arjun! I have a few ideas how to overcome these issues. We can discuss it during the next public conf-call!

**Comment by gfursin** [comment]
One quick idea is to use - in front of the tag to skip entries with this tag ...

**Comment by arjunsuresh** [comment]
That's nice. Meaning "minus" :)

**Comment by gfursin** [comment]
Exactly!

By the way, couple of things:

1) I think that unless we see the real need for that for our current goals, we can leave the implementation for later. But it's just good to make sure that we do not break backwards compatibility in the future ...

2) Another idea is to separate tags that are used inside the CM core search function (to ensure direct and quick search) and the ones that are used to specialize CM components (such as versions/variations). Maybe rather than having "v-" for variations, we could have a special prefix such as ~ that tells CM core search to ignore it and then let CM components deal with these extra tags further in the pipeline (such as specializing meta packages). 

3) I start thinking that maybe we should have a separate flag for tags and variations because the meaning is different ... One searches for CM artifacts while another updates a meta description ...

```
cm obj search --tags=framework,tensorflow --variations=v2.5.1,cuda
```

Will need to discuss that further ...

**Comment by gfursin** [comment]
We think to use a separate flag to specify version that will be converted into tags and env key to be used in an IC customize.py or run script:
```
cm run ic --tags=get,llvm,bin --version=14.0.0
```

**Comment by gfursin** [comment]
We have finalized that in the latest release.
