### ISSUE TITLE
Which CMD format should we use (2 variants)

### ISSUE THREAD

**Issue by gfursin** [mlcommons/ck#209]
When I designed CK CMD, I wanted to use it similar to natural language:
```bash
ck {action} {automation}:{data}
```
i.e. ```ck run program:mlperf-inference```

I had 50/50 feedback about this CMD. Some people liked it and some preferred Git-like style:
```bash
ck {automation} {action} {data}
```

In CM I decided to use the last one:
```bash
cm {automation} {action} {artifact} (artifact1) (artifact2)
```

But the more I use it the more I like the first one:
```bash
cm {action} {automation} {artifact1} (artifact2) ...
```

i.e.

```bash
cm run program mlperf-inference
```

I just don't use : here. In such case, I could specify repos for both automations and artifacts, i.e.
```bash
cm run default:program octoml@cm-mlops:mlperf-inference
```

Any preference?

@arjunsuresh @hanwenzhu ?

I would like to stabilize it ASAP to focus on the new CM components ...

**Comment by gfursin** [comment]
Another alternative is to use :: to separate automation and artifact, and : to separate repos:
```bash
cm run default:program::octoml@cm-mlops:mlperf-inference
```

Need to think about that ...

**Comment by hanwenzhu** [comment]
Hi Grigori, I like the space-separated ones more because it's a clearer visual separation, like git commands.

**Comment by gfursin** [comment]
Hi Thomas! Thank you for your feedback! 
I think I prefer this format too. I believe we will change the current CM CLI back to CK style with spaces:
```bash
cm add repo my-cool-project --flags
```
I plan to prototype that this week ...

**Comment by gfursin** [comment]
Updated in the latest commit: https://github.com/mlcommons/ck/commit/c64c50d7ef584354fb3638a432539d97f0479a6c
