### ISSUE TITLE
[CK2/CM] Create different Docker containers to test CM

### ISSUE THREAD

**Issue by gfursin** [mlcommons/ck#212]

**Comment by gfursin** [comment]
We can use https://github.com/mlcommons/ck-mlops/tree/main/docker/ck-mlperf-inference-dev-image-classification-onnx-tvm as example.

**Comment by arjunsuresh** [comment]
We now have test for [Ubuntu (22.04)[(https://github.com/mlcommons/ck/blob/master/tests/script/test_docker.py). CentOS support needs to be added for docker.
