### ISSUE TITLE
[CK2/CM components] add unique name and ID in deps in intelligent components 

### ISSUE THREAD

**Issue by gfursin** [mlcommons/ck#231]
Need that to update their tags (variations) or skip them ...

**Comment by gfursin** [comment]
Hi @arjunsuresh . 

In the latest commit of "script" automation I've added the "name" key to deps (note that it's a list of names and UIDs).

I also added optional "deps" keys to variations to be merged with the list of current deps.

Finally, I added the "add_deps_tags" key to variations to update deps (referenced by name/UID) with tag(s) separated by comma: ({"name":"tag(s)"}). The same can be done from CMD: 
```bash
cm run ic ...  --add-deps-tags.name=tag(s)
```

Please feel free to test it and tell me if it works for you! Thanks a lot for the discussion and suggestions!

**Comment by gfursin** [comment]
I also added an example here: https://github.com/octoml/cm-mlops/blob/main/script/prototype-test-deps-variations-tags/_cm.json#L30

```
$ cm run script --tags=test,deps-variations-tags,_1.5-opset-11
```

This variation will add print hello world script ...

**Comment by gfursin** [comment]
Hey @arjunsuresh - I think this is working now. It's not urgent but when you have time, can you please test it and close this ticket if it works? Thanks a lot!

**Comment by arjunsuresh** [comment]
Thank you Grigori. It works fine.
