### ISSUE TITLE
[CK2/CM components] Simplify handling of lists in env

### ISSUE THREAD

**Issue by arjunsuresh** [mlcommons/ck#234]
Currently the logic to handle list in env is a bit complex. We can possibly make this simpler by using a special prefix for such variables - say '&'.
https://github.com/mlcommons/ck/blob/master/ck2-repo-mlops/automation/ic/module.py#L703

**Comment by gfursin** [comment]
Done in https://github.com/mlcommons/ck/commit/7bf99b796df387bbd6c77dfa39703c63fb4fbecc .
I use prefix "+" in env key to indicate that the same key should be appended at the end:
```
{"+PATH":"something"} -> PATH=something:$PATH ...
```
