### ISSUE TITLE
[CK2/CM scripts] discuss and unify how to reinstall/rebuild packages

### ISSUE THREAD

**Issue by gfursin** [mlcommons/ck#238]
Installation of packages often requires multiple steps:
* clone/download sources
* configure
* build
* install

If it fails, we want to be able to restart such CM scripts from any stage. Can we unify it?

**Comment by arjunsuresh** [comment]
Can we use a universal clone script which can be used as a prehook_dependency to do git clone? Similarly we can use a universal configure and build scrips as posthook_dependency. We need to decide how the results of such universal scrips can be cached.
