### ISSUE TITLE
[CK2/CM scripts] issue with Docker wrapper for image classification

### ISSUE THREAD

**Issue by gfursin** [mlcommons/ck#255]
Hi @arjunsuresh . I tried the wrapper for image classification and I think there is an issue:

The CMD var is never called in https://github.com/mlcommons/ck/blob/master/cm-mlops/script/wrapper-image-classification-onnx-py/customize.py#L16 and the "docker_exists" never found.

Should we add os.system(CMD) there?

Thanks!

**Comment by arjunsuresh** [comment]
Oops. Just fixed this https://github.com/mlcommons/cm-mlops/commit/11e28ac4aa3554cf75a0d71b5a926c75e15353ad

**Comment by gfursin** [comment]
Cool! Thanks @arjunsuresh !
