### ISSUE TITLE
[CK2/CM scripts] Option to update env variable in meta, only if it is not existing (default_env)

### ISSUE THREAD

**Issue by arjunsuresh** [mlcommons/ck#260]
Currently any env variable specified in meta override the same from the incoming env. For example, in this [script](https://github.com/mlcommons/ck/blob/master/cm-mlops/script/build-dockerfile/_cm.json#L21), env variable is used to specify the base docker image and there is no way for any parent script to override this. I see two possible ways to fix this. One is to use a prefix '?' for the key like here.

```env[?KEY] = ...```

Alternatively, we can use a separate dictionary say `default_env` which will be merged with env with already existing keys being removed.

**Comment by gfursin** [comment]
Yes, I saw it and we need to discuss what is the best way to update it. My original idea was to use --const to update such env (it already works) but maybe it's not the best mechanism. Let's discuss it during our next meeting ... Thanks!

**Comment by arjunsuresh** [comment]
Hi @gfursin, I feel `default_env` is the best approach here as this is coming only inside meta. What do you think?
