### ISSUE TITLE
[CK2/CM] Problem with excluding a variation tag in dependency

### ISSUE THREAD

**Issue by arjunsuresh** [mlcommons/ck#263]
Currently the following way of adding a dependency is causing error in `install-mlc-inference-loadgen` script. 

```
      "deps": [
        {
          "tags": "get,mlcommons,inference,src,-_patch",
          "version": "r2.1"
        }
      ]
```

**Comment by gfursin** [comment]
Hmm, that's weird. Let me check that ...

**Comment by arjunsuresh** [comment]
Seems to be working now. But more tests can be useful.
