### ISSUE TITLE
[CK2/CM] Adding an option to specify version of a dependency via CLI

### ISSUE THREAD

**Issue by arjunsuresh** [mlcommons/ck#264]
Currently we have a way to specify variation or tags of a dependency by using `--add_deps_tags` option but there is no clean way by which we can force a specific version of a dependency. Something like the following will be useful for CM scripts.

1. `--add_deps_version`
2. `--add_deps_version_min`
3. `--add_deps_version_max`
4. `--add_deps_version_max_usable`

With these we get complete flexibility in controlling any direct dependency of a script.

**Comment by gfursin** [comment]
Hi Arjun.

It's a good idea but maybe we can just keep one flag and specify min/max/max_usable as an argument?

Something like
```
--add-deps-version.ID=1.12.0     # this sets version of a dependency with ID
--add-deps-version.ID=1.12.0,min=...,max=..., # sets extras 
```

However, if it looks complex, we can keep your flags ... I am fine with that too ... Thanks!

**Comment by arjunsuresh** [comment]
Thank you Grigori for your reply. I was thinking if we should make a dictionary for add_deps and then we can use version, version_min, version_max, version_max_usable as well as tags and post_tags as it's keys like shown here. 
`add_deps.version.<dep_name>`, `add_deps.tags.<dep_name>` etc.

This way we'll have a uniform way of controlling any dependency at the same time keeping the syntax simple. What would you suggest?

**Comment by gfursin** [comment]
Thank you for the discussion today, @arjunsuresh . I agree with your proposal o update deps universally via a dictionary - it will be  easy to extend ...

**Comment by arjunsuresh** [comment]
Thank you Grigori. This seems to be working now.

**Comment by arjunsuresh** [comment]
I think we should pass on `add_deps` recursively to all dependencies. This way we can fix certain dependencies at runtime like follows
```
--add_deps.compiler.tags=gcc --add_deps.python3.version=3.9.12
```
@gfursin What do you think? This change seems to work fine for me.

**Comment by gfursin** [comment]
> I think we should pass on `add_deps` recursively to all dependencies. This way we can fix certain dependencies at runtime like follows
> 
> ```
> --add_deps.compiler.tags=gcc --add_deps.python3.version=3.9.12
> ```
> 
> @gfursin What do you think? This change seems to work fine for me.

Hi @arjunsuresh. I agree with that! Thanks!
