### ISSUE TITLE
[CK2/CM project] implement modular ML benchmarking and design space exploration based on loadgen and CK2(CM)

### ISSUE THREAD

**Issue by gfursin** [mlcommons/ck#265]
The goal of this project (summer internship of Thomas Zhu from Oxford University) is to prototype CM-based modularization of the MLPerf inference benchmark to connect [C++ loadgen](https://github.com/mlcommons/inference/tree/master/loadgen) with different ML models, data sets, engines, libraries and platforms. The outcome of this internship will be presented to MLCommons for further community developments within the [MLPerf education WG](https://github.com/mlcommons/ck/blob/master/docs/mlperf-education-workgroup.md).

Plan:
* Develop CM automation to run MLPerf image classification with a reference ML model and dataset (RESNET50 and ImageNet) using C++-based loadgen with ONNX and TVM.
* Extend CM automation to run any ML model and dataset with MLPerf image classification.
* Generate modular MLPerf containers assembled from CM basic blocks.
* Discuss with MLCommons how to adopt CM automation for MLPerf crowd-benchmarking.

**Comment by gfursin** [comment]
Conf-call 20220810: (@arjunsuresh - @hanwenzhu). Explained about the C++ image classification application we need for interacting with loadgen and also support multiple devices in a scalable way. For now, the device will be onnxruntime. Also had a quick walk through for the C++ code used for Qualcomm Cloud AI MLPerf submissions.

**Comment by gfursin** [comment]
Conf-call 20220830: @hanwenzhu made a good progress and plan to deliver the first prototype of a modular MLPerf image classification task combined with loadgen (without CM automation for now) within a week. 
No problems encountered but it take longer time because Thomas checks C++ implementations from different organizations to make sure that his implementation is efficient and extensible.

**Comment by hanwenzhu** [comment]
(Bug) I ran the first example script and there was a very weird accuracy 1%. I checked the mlperf_log_accuracy.json and it appears all samples are classified as label 366. I think thats an issue upstream with ONNXRuntime. The problem is fixed once I set the graph optimization level to 2 (`opt.graph_optimization_level = rt.GraphOptimizationLevel.ORT_ENABLE_EXTENDED`) near line 30 of backend_onnxruntime.py. The default level 3 (`ORT_ENABLE_ALL`) doesn't work for M1 - I also encountered this problem in C++.

**Comment by gfursin** [comment]
We have added the tutorial to use the modular C++ implementation of the MLPerf (huge thanks to @hanwenzhu for these developments): https://github.com/mlcommons/ck/blob/master/docs/tutorials/sc22-scc-mlperf2.md . We will continue extending it based on the new roadmap: https://github.com/mlcommons/ck/issues/536
