### ISSUE TITLE
[CK2/CM] Overriding variables in new_env 

### ISSUE THREAD

**Issue by arjunsuresh** [mlcommons/ck#272]
Currently due to [this](https://github.com/mlcommons/ck/blob/master/cm-mlops/automation/script/module.py#L2047) condition if a variable is already in saved_env, it is not getting saved in the cached entry.

**Comment by arjunsuresh** [comment]
This partial fix handles override of env when it is a simple variable. Logic for handling "list" variables and also state variables need to be added.

**Comment by gfursin** [comment]
Thanks Arjun! As we discussed during the conf-call today, it makes sense but we can leave fixing state variables for later ...

**Comment by gfursin** [comment]
I think we can close this ticket?

**Comment by arjunsuresh** [comment]
I think we can add a quick fix for state variables too as list part is already good. I'll add a PR soon and close this ticket.

**Comment by gfursin** [comment]
Cool! Thanks a lot!
