### ISSUE TITLE
[CK2/CM] Feature to reconstruct cm command

### ISSUE THREAD

**Issue by arjunsuresh** [mlcommons/ck#276]
It would be nice to have an option to reconstruct a cm run command from inside any script. This way we can automatically add such commands to any possible README files as well as log files.

**Comment by gfursin** [comment]
Hi @arjunsuresh . I agree that it can be useful ... As we discussed today, there are multiple ways of doing it. We will likely have to set up some env variable (CM_LOG_COMMAND), create a list of commands in the CM class and then record commands there in the cli.py ... Something like that. Please feel free to check it out ... Thanks!!!

**Comment by arjunsuresh** [comment]
Thank you @gfursin. This [commit](https://github.com/mlcommons/ck/commit/676b3753ea47c074fe742192bc62eb0a019cf132) fixes this.
