### ISSUE TITLE
[CK2/CM] CM_TMP_FAIL_IF_NOT_FOUND causes script failure

### ISSUE THREAD

**Issue by arjunsuresh** [mlcommons/ck#290]
We are setting as below in `install` script and this is used in `get` script.
```env['CM_TMP_FAIL_IF_NOT_FOUND'] = 'yes'```
But if multiple such `get` scripts are run as dependencies then this will cause the failure of the second script as `env['CM_TMP_FAIL_IF_NOT_FOUND'] = 'yes'`. 
We need a way to handle this recursion. 

Currently, this error can be seen on Ubuntu 22.04 (default python is 3.10) for the below command (this will call `install,python,src` as a dependency)
```
cm run script --tags=get,onnxruntime
```

**Comment by arjunsuresh** [comment]
@gfursin Is this fix fine?

**Comment by gfursin** [comment]
Thank you for noting that @arjunsuresh . Let me check it today!
