### ISSUE TITLE
Creating a catalog of CM (CK2) automations for (MLPerf/ML/AI) artifacts and tools

### ISSUE THREAD

**Issue by gfursin** [mlcommons/ck#296]
I suggest to create a catalog of [CM automations](https://github.com/mlcommons/ck/tree/master/cm-mlops/script) for MLPerf/ML/AI artifacts and tools that can be reused across projects.

We can add it to the root README with links to above automations at https://github.com/mlcommons/ck/tree/master/cm-mlops . Something like:
# Compilers
# Containers
# Aux tools
# ML models
# ML datasets
# ML engines
# Benchmarks
# Apps

Any thoughts?

**Comment by arjunsuresh** [comment]
Sure Grigori. I think we can have a table for each which will include the supported OS as well.

**Comment by arjunsuresh** [comment]
Hi @gfursin, below is a summary of these as of now. 
 
# Compilers
* [gcc](https://github.com/octoml/ck/tree/master/cm-mlops/script/get-gcc)
* [llvm](https://github.com/octoml/ck/tree/master/cm-mlops/script/get-llvm)
* [cuda](https://github.com/octoml/ck/tree/master/cm-mlops/script/get-cuda)
# Containers
* [docker for Ubuntu 18.04, 20.04, 22.04 and RHEL9](https://github.com/octoml/ck/tree/master/cm-mlops/script/build-dockerfile/dockerfiles) 
# Aux tools
* [zephyr](https://github.com/octoml/ck/tree/master/cm-mlops/script/get-zephyr)
* [zephyr-sdk](https://github.com/octoml/ck/tree/master/cm-mlops/script/get-zephyr-sdk)
* [bazel](https://github.com/octoml/ck/tree/master/cm-mlops/script/get-bazel)
* [dnnl](https://github.com/octoml/ck/tree/master/cm-mlops/script/get-lib-dnnl)
# ML models
* [resnet50 onnx](https://github.com/octoml/ck/tree/master/cm-mlops/script/get-ml-model-resnet50-onnx), [pytorch](https://github.com/octoml/ck/tree/master/cm-mlops/script/get-ml-model-resnet50-pytorch) and [tensorflow](https://github.com/octoml/ck/tree/master/cm-mlops/script/get-ml-model-resnet50-tf) (fp32)
* [retinanet onnx and pytorch](https://github.com/octoml/ck/tree/master/cm-mlops/script/get-ml-model-retinanet) (fp32)
# ML datasets
* [imagenet]()
* [imagenet preprocessed]()
* [openimages]()
# ML engines
* [tensorflow](https://github.com/octoml/ck/tree/master/cm-mlops/script/get-tensorflow)
* [onnxruntime](https://github.com/octoml/ck/tree/master/cm-mlops/script/get-onnxruntime)
* [pytorch](https://github.com/octoml/ck/tree/master/cm-mlops/script/get-pytorch)
* [tvm](https://github.com/octoml/ck/tree/master/cm-mlops/script/get-tvm)
# Benchmarks
* [MLPerf inference image classification, object detection](https://github.com/octoml/ck/tree/master/cm-mlops/script/app-mlperf-inference-vision-reference)
# Apps
* [Image classification onnx](https://github.com/octoml/ck/tree/master/cm-mlops/script/app-image-classification-onnx-py), [Onnx cpp](https://github.com/octoml/ck/tree/master/cm-mlops/script/app-image-classification-onnx-cpp), [pytorch](https://github.com/octoml/ck/tree/master/cm-mlops/script/app-image-classification-torch-py)
* [Image corner detection]()
* [MLPerf inference vision run and submission generation from reference code](https://github.com/octoml/ck/tree/master/cm-mlops/script/generate-mlc-inference-submission)
* [MLPerf image classification and submission generation from CPP code](https://github.com/octoml/ck/tree/master/cm-mlops/script/app-mlperf-inference-cpp)

**Comment by gfursin** [comment]
Thanks! Done!
