### ISSUE TITLE
[CK2/CM] Transparently handling variations inside get scripts corresponding to install scripts

### ISSUE THREAD

**Issue by arjunsuresh** [mlcommons/ck#305]
As discussed during our conf call, to pick the corresponding variation from the install script, we can create empty variations inside get scripts for all the variations in the corresponding install scripts. 

We'll also need an option like "PASS_VARIATION_TAGS_TO_POST_DEPS" to pass the variations of the get script to the corresponding install script.

**Comment by arjunsuresh** [comment]
I think "PASS_VARIATION_TAGS_TO_POST_DEPS" may not be a good solution as we might have multiple post_deps for a script. Instead we can have `add_to_deps` list inside each variation where the variation, if on, will add the variation tag to the list of dependencies specified in the list. We can also have an option for each dependency - `inherit_all_variation_tags` which if on will add all the variation tags to its own tags.

**Comment by gfursin** [comment]
As discussed today, I think it makes sense.
