### ISSUE TITLE
[CM scripts] download Git repos without history

### ISSUE THREAD

**Issue by gfursin** [mlcommons/ck#314]
As we discussed today, the total size of MLPerf inference repo is 440MB. However, without history, it's only 5MB. 
The idea is to add an ENV (maybe CM_SKIP_GIT_HISTORY) to skip history in scripts when pulling such repos?
It can be used in "cm pull repo" and in "cm run script" ... Can discuss it further ...

**Comment by arjunsuresh** [comment]
This is fixed now using `--depth` git clone option. Moreover we now are not downloading git-submodules except `pybind` by default.

**Comment by gfursin** [comment]
Cool! Thanks a lot!!!
