### ISSUE TITLE
[CK2/CM] Can we have post_preprocess_deps and pre_postprocess_deps?

### ISSUE THREAD

**Issue by arjunsuresh** [mlcommons/ck#321]
Currently we have "deps" which are executed before a script invocation and "post_deps" which are executed after a script invocation. But we do not have an option to run a cm script immediately after the preprocess function or immediately before the postprocess function. I think it'll be a good idea to have `post_preprocess_deps` and `pre_postprocess_deps` to add this functionality. This functionality can be useful in the following scenario

We have an application code in Python and C (both as independent CM scripts) and a CM wrapper script for both. We can now prepare the language independent inputs for the application in the preprocess function and depending on the language chosen (handled as variations) we can call the respective scripts as `post_preprocess_deps` which will do the actual application run and finally in the postprocess function we can process the produced outputs. Similarly, `pre_postprocess_deps` can also be useful as in the case of `python-venv`.

**Comment by gfursin** [comment]
Hi Arjun. Thank you for suggestion. As we discussed this morning, I think it's a good idea. It will give users a complete programmatic and functional control of CM scripts, CM sub-scripts and native scripts:
* deps (dynamic execution of other CM scripts - can be skipped in cache (such as large datasets))
* preprocess [Python + meta + env]
* prehook_deps (or whatever is the standard name) [dynamic execution of other CM scripts customized by preprocess and deps]
* native OS script (any native user script on any OS/hardware)
* /update env and state from native OS script/
* posthook_deps (or whatever is the standard name) [dynamic execution of other CM scripts customized by OS script)
* postprocess [Python + meta + env]
* post_deps [dynamic execution of other CM scripts]
