### ISSUE TITLE
[CK2/CM] Converting inputs to env variables for scripts

### ISSUE THREAD

**Issue by arjunsuresh** [mlcommons/ck#333]
As per convention we are mostly using only env variables to pass in information to any CM script and these variables are in capital letters. When the number of inputs are large this may not be convenient for users to type in such inputs as env variables. It makes sense to have a list of inputs per script which will be automatically converted to env variables with a predefined prefix. For example,
```
--output_dir -> CM_OUTPUT_DIR
--rerun -> CM_RERUN
--count -> CM_MLPERF_QUERY_COUNT
```
These mappings can be specified in the meta description of the script.

**Comment by gfursin** [comment]
That's a good idea, Arjun! I believe we can define such inputs in meta of a given script, right?

**Comment by arjunsuresh** [comment]
yes Grigori. By adding in _cm.json we are documenting them also :)
