### ISSUE TITLE
CM script is not getting cached in some cases

### ISSUE THREAD

**Issue by arjunsuresh** [mlcommons/ck#372]
Suppose we have `install,python,version-3.9.12` in cache. In such a case if we do the following command, the get,script will fail and calls the `install-script`. But since the `install-script` is in cache, the get,script is not called and hence no cache entry added. We can force call the `get-script` even from cache but we need a way to pass the CM_TMP_PATH to the `get-script`. 
```
cm run script --tags=get,python --version=3.9.12
```

**Comment by gfursin** [comment]
We will prototype a new workflow with prehook_deps as discussed today.
