### ISSUE TITLE
cmake: command not found CM error: Portable CM script failed (return code = 256)

### ISSUE THREAD

**Issue by Patel230** [mlcommons/ck#377]
While running the below commands, "command not found CM error" I got.

For accuracy:
"cm run script --tags=app,mlperf,_resnet50,python,_onnxruntime  --output_dir=$HOME/final_results \
--mode=performance --scenario=Offline \
--add_deps.loadgen.version=r2.1 --adr.inference-src.tags=_octoml"

For Performance:

"cm run script --tags=app,mlperf,_resnet50,python,_onnxruntime  --output_dir=$HOME/final_results \
--mode=accuracy --scenario=Offline \
--add_deps.loadgen.version=r2.1 --adr.inference-src.tags=_octoml "

![1](https://user-images.githubusercontent.com/17196758/193103012-12e64628-325e-4363-83f9-48a70776b5ab.jpeg)

**Comment by arjunsuresh** [comment]
This should be fixed with [this](https://github.com/mlcommons/ck/pull/376) change.

**Comment by gfursin** [comment]
@Patel230: Thank you for your feedback, Lakshman - very appreciated! 
We've added you to the contributors to Ck and CM: https://github.com/octoml/ck/blob/master/CONTRIBUTING.md - we will merge it with the MLCommons branch in the next PR!

**Comment by Patel230** [comment]
Thank you so much @gfursin , i will contribute more.
