### ISSUE TITLE
Before installing gcc I'm getting below error

### ISSUE THREAD

**Issue by Patel230** [mlcommons/ck#380]
Please see the attached screenshots.
![msg-1684754655-64 (1)](https://user-images.githubusercontent.com/17196758/193309468-058b6967-a5b0-4723-954a-92921cdcc7a3.jpg)
![msg-1684754655-65 (1)](https://user-images.githubusercontent.com/17196758/193309475-c20620ef-0f60-4c80-936d-8834e9aee49b.jpg)

**Comment by arjunsuresh** [comment]
@Patel230 Can you please tell which exact command caused this error? And also the version of Ubuntu.

**Comment by arjunsuresh** [comment]
This issue is same as the first one given [here](https://github.com/octoml/ck/blob/master/cm/meetings/notes-20220930.md#must-be-fixed)

**Comment by Patel230** [comment]
Sorry for the delay from my side,  "cm run script --tags=app,mlperf,_resnet50,python,_onnxruntime  --output_dir=$HOME/final_results \
--mode=performance --scenario=Offline \
--add_deps.loadgen.version=r2.1 --adr.inference-src.tags=_octoml " this one.
And I'm using ubuntu 22.04

**Comment by arjunsuresh** [comment]
Hi @Patel230 , this issue should be fine now. On Linux, cl compiler won't be picked up anymore.
