### ISSUE TITLE
Documenting the flow of env variables in CK2/CM script automation

### ISSUE THREAD

**Issue by arjunsuresh** [mlcommons/ck#382]
We need to show how env variables (and state) are propagating in our new CK2/CM script automation workflow

**Comment by arjunsuresh** [comment]
![CM script env flow](https://user-images.githubusercontent.com/4791823/193423542-a17557b3-ca04-4090-a607-27ef851b4078.png)

**Comment by arjunsuresh** [comment]
The above figure describes a high level flow for `env`. Flow is similar for `state`. At each step `env` can be updated.

**Comment by gfursin** [comment]
We continue working on that: https://docs.google.com/spreadsheets/d/1T5-c7Eb8CfUxgwYgxQND-UsWWJY-I4lDNqK5DZM9uV4/edit#gid=0

**Comment by gfursin** [comment]
@arjunsuresh - we still need to update it in our "scripts" doc (it's outdated). I will reopen the ticket - let's try to do it next week ...
