### ISSUE TITLE
Mix up when pulling first mlcommons@ck repo and then octoml@ck repo.

### ISSUE THREAD

**Issue by arjunsuresh** [mlcommons/ck#397]
Adding this pending issue from our [meeting notes](https://github.com/mlcommons/ck/blob/master/cm/meetings/notes-20220930.md#must-be-fixed).

We need to check that alias is the same and then do not allow pulling while doing `cm pull repo`

PRINT CM REPO ALIAS AFTER PULLING: "you can reference this CM repo using alias "mlcommons@cm-mlops" ...

**Comment by gfursin** [comment]
Fixed in https://github.com/octoml/ck/commit/0f43b0160e640c5676682afcb53dabaf57de785f
