### ISSUE TITLE
Create a universal python library installer

### ISSUE THREAD

**Issue by arjunsuresh** [mlcommons/ck#410]
We should create a universal CM script to install python-libs using variations.

**Comment by arjunsuresh** [comment]
CM script for [universal python-lib installation](https://github.com/mlcommons/ck/tree/master/cm-mlops/script/get-python-lib) is created. We need to move existing scripts to this one.

**Comment by xintin** [comment]
I am trying to run `test_deps.py` under `tests/script/`.  
The following test:
```
r = cm.access({'action':'run', 'automation':'script', 'tags': 'app,mlperf,inference,python,_resnet50,_onnxruntime,_cpu,_r2.1_default', 'quiet': 'yes'})
checks.check_return(r)
```
is throwing an exception: 
`Exception: variable CM_ONNXRUNTIME_VERSION is not in env`

**Comment by arjunsuresh** [comment]
Thank you @xintin for reporting. This issue should be fixed now.
