### ISSUE TITLE
Report time spent in CM scripts and their dependencies

### ISSUE THREAD

**Issue by gfursin** [mlcommons/ck#414]
When preparing [reproducibility reports for MLPerf](https://github.com/mlcommons/ck/blob/master/docs/mlperf-automation-cm/reproducibility.md), we've realized that it would be useful to provide a report about individual time spent in scripts and their dependencies. We can do it automatically - just need to think how to do it (printing time after execution of each script or as a report at the end of the main script)...

**Comment by arjunsuresh** [comment]
I think we can update the print to console like follows (adding the time taken) for script execution. 
```
- run preprocess ... (took 2s)
- run script ... (took 28.6 s)
- run postprocess ... (took 0.5s)
```

At the end of a script execution we can also print the total time taken for it  (similar to the time command). In addition whenever any script is cached, we can add the time to produce the cached entry to the meta in the cache.

**Comment by gfursin** [comment]
I like that!

**Comment by gfursin** [comment]
Prototyped here: https://github.com/octoml/ck/commit/0410f942fd25c438113784d51083310b66042522

**Comment by gfursin** [comment]
@arjunsuresh - let's check it together ...

**Comment by gfursin** [comment]
Done.
