### ISSUE TITLE
Feedback on running the MLPerf inference benchmark - SCC

### ISSUE THREAD

**Issue by xintin** [mlcommons/ck#492]
Few observations, 

1. Under [Prepare MLPerf Submission](https://github.com/mlcommons/ck/blob/master/docs/tutorials/sc22-scc-mlperf.md#prepare-mlperf-submission), the command usages all 40 cores (my available physical cores) for the intermediate processing. I assume this is intentional. Can the num_threads (like param) be passed with the command to limit the num_threads (or added to the tutorial to be set as env var)?

`INFO:main:Namespace(accuracy=False, audit_conf='audit.config', backend='onnxruntime', cache=0, cache_dir='/data/gverma/scc/repos/local/cache/d6bf17bab32a4ab9', count=10, data_format=None, dataset='openimages-800-retinanet-onnx', dataset_list=None, dataset_path='/data/gverma/scc/repos/local/cache/5981e9a02c0744a4/install', debug=False, find_peak_performance=False, inputs=['images'], max_batchsize=1, max_latency=None, mlperf_conf='/data/gverma/scc/repos/local/cache/f0390d25b55a49ec/inference/mlperf.conf', model='/data/gverma/scc/repos/local/cache/52184bdcc34245a9/resnext50_32x4d_fpn.onnx', model_name='retinanet', output='/data/gverma/scc/repos/local/cache/f0390d25b55a49ec/inference/vision/classification_and_detection/test_results/onnxruntime-cpu/retinanet/offline/performance/run_1', outputs=['boxes', 'labels', 'scores'], performance_sample_count=None, profile='retinanet-onnxruntime', qps=None, samples_per_query=8, scenario='Offline', threads=40, time=None, user_conf='/data/gverma/scc/repos/mlcommons@ck/cm-mlops/script/app-mlperf-inference/tmp/101ad149b83644e68b94470a69e24f50.conf')`

2. Log file for the above run can be found [here](https://drive.google.com/file/d/1HlgMZW5QQCHLgYpGS_7uoEljCQ1O0o_S/view?usp=sharing). I could see some errors, but they can be ignored as reasonable. Still, you can have a look at them.

The important thing is after the successful run, I do not see open.tar.gz and summary.* files in my current dir, as mentioned in the tutorial. Although, in my $HOME directory, I do have a folder result/ and result_logs/. Is the tar command not executing correctly? `$CM_REPOS` is set to the current dir.
Log says,
```
tar --directory /home/gverma/results -czf /data/gverma/scc/open.tar.gz open
Tar file /data/gverma/scc/open.tar.gz created
```
But no tar or summary files are present.

Thank you and Kind regards.

**Comment by gfursin** [comment]
Thank you very much for the feedback @xintin . I believe we have fixed a few small bugs and updated the docs (you can use --num_threads flag to select number of threads for MLPerf). By the way, I also added a section to use virtual python. Do you think you can try the latest version with virtual environment as follows, please (you can clean cache to make sure that it's a clean environment)?

```
cm pull repo mlcommons@ck

cm rm cache -f

cm run script "install python-venv" --version=3.10.7 --name=mlperf

cm run script --tags=run,mlperf,inference,generate-run-cmds,_submission,_short,_dashboard $CMX \
      --adr.python.extra_cache_tags=venv-mlperf \
      --adr.python.version_min=3.8 \
      --adr.compiler.tags=gcc \
      --adr.openimages-preprocessed.tags=_500 \
      --submitter="OctoML" --hw_name=default \
      --model=retinanet --backend=onnxruntime --device=cpu \
      --scenario=Offline --test_query_count=10 --rerun

```

Thank you very much for your help!

**Comment by xintin** [comment]
It is working as expected. 
Thank you.

**Comment by gfursin** [comment]
Perfect! Thank you very much!!!
