### ISSUE TITLE
CM script "get cuda" doesn't respect --version_min

### ISSUE THREAD

**Issue by gfursin** [mlcommons/ck#505]
I have CUDA 11.1 installed. When I run `cm run script "get cuda" --version_min=11.3, it detects my installation version and still registers it in cache which is not correct. It should either fail or try to install a new binary with the latest CUDA ... Let's check it...

**Comment by gfursin** [comment]
Weird, because "get python" works fine with --version_min and --version_max ..

**Comment by arjunsuresh** [comment]
yes, it seems the issue is happening when we have the entry cached. I added a test script which has a deps 
``` {
      "tags": "get,generic-python-lib,_torch",
      "version_max": "1.10.0"
    }
```
to test this. The script works fine if `get,generic-python-lib,_torch` is not in the cache.
```
cm run script --tags=test,script5
```

**Comment by arjunsuresh** [comment]
Hi @gfursin the above commit should fix this issue. We were not recording the version in the meta.
