### ISSUE TITLE
[Bug] run-mlperf-inference-app script fails when --submitter has a space

### ISSUE THREAD

**Issue by gfursin** [mlcommons/ck#553]
Hi @arjunsuresh. Our script https://github.com/mlcommons/ck/tree/master/cm-mlops/script/run-mlperf-inference-app fails when --submitter has a space. I think it's a relatively simple thing but it will be good to fix it. Do you mind to check it, please? Thanks a lot!

**Comment by arjunsuresh** [comment]
Hi @gfursin , I have fixed this but then the submission checker fails
```
[2022-11-18 10:09:07,845 submission_checker1.py:1928 ERROR] open/Test ML contains files with spaces in their names: ['open/Test ML']
```

**Comment by gfursin** [comment]
Thanks! Interesting! Can we substitute spaces with "-" for the directory there?

**Comment by gfursin** [comment]
Alternatively, we can keep submitter name as a short abbreviation and add "full_submitter_name" that we can use internally for the dashboard?

**Comment by arjunsuresh** [comment]
Sure Grigori. We can discuss this over the call.

**Comment by gfursin** [comment]
Should move to cm4mlops.
