### ISSUE TITLE
CUDA instalation error

### ISSUE THREAD

**Issue by pgmpablo157321** [mlcommons/ck#571]
I am getting an error when trying to install cuda in GCP compute engine.
## Instance:
**Machine type:** n1-standard-2
**GPU:** NVIDIA Tesla P4
**OS:** Ubuntu 18.04 LTS
**GCP command:**
```
gcloud compute instances create test-cm --project=mlperf-validation --zone=us-central1-a --machine-type=n1-standard-2 --network-interface=network-tier=PREMIUM,subnet=default --maintenance-policy=TERMINATE --provisioning-model=STANDARD --service-account=217413023279-compute@developer.gserviceaccount.com --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append --accelerator=count=1,type=nvidia-tesla-p4 --create-disk=auto-delete=yes,boot=yes,device-name=test-cm,image=projects/ubuntu-os-cloud/global/images/ubuntu-1804-bionic-v20221125,mode=rw,size=100,type=projects/mlperf-validation/zones/us-central1-a/diskTypes/pd-balanced --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --reservation-affinity=any
```
## CM Command
```
cm run script "get cuda" --out=json
```
## Error
<img width="410" alt="Screen Shot 2022-11-30 at 12 55 32 PM" src="https://user-images.githubusercontent.com/30699846/204872427-1ee204dd-8e23-4e4f-9bf1-e1e1b976ecd4.png">

/tmp/cuda-installer.log:
<img width="440" alt="Screen Shot 2022-11-30 at 12 56 46 PM" src="https://user-images.githubusercontent.com/30699846/204872662-0fa7c764-9491-4d14-aefb-58838fa5d692.png">

When running the installation as root, I can pass the cuda installation. But when running the benchmark I get this error:
```
2022-11-14 21:22:34.724320565 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:535 CreateExecutionProviderInstance]
Failed to create CUDAExecutionProvider.
Please reference https://onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html#requirements to ensure all dependencies are met.
```

**Comment by gfursin** [comment]
@arjunsuresh . I believe we should add ${CM_SUDO} before running driver installation and turn it on (set it to "sudo") with an explicit flag in CLI "--sudo"... 

As for the tensorrt issue - can you please check if it can be solved by pip package - we can then add it as dependency ...

@pgmpablo157321 - the second issue seems to be only related to Python implementation. Can you run our C++ implementation with CUDA to check if it works fine using [this tutorial](https://github.com/mlcommons/ck/blob/master/docs/tutorials/sc22-scc-mlperf2.md#mlperf-inference---c---retinanet-fp32---open-images---onnx---gpu---offline), please?

Thank you very much for your feedback - we can discuss it more tonight if you are available!

**Comment by pgmpablo157321** [comment]
After installing cuda manually I get the following error:

```
Scenario: Offline
Mode: PerformanceOnly
Batch size: 1
loaded openimages with 10 samples
starting benchmark
loading samples to ram
node 0 running batch #6-#6
terminate called after throwing an instance of 'Ort::Exception'
  what():  There's no data transfer registered for copying tensors from Device:[DeviceType:1 MemoryType:0 DeviceId:0] to Device:[DeviceType:0 MemoryType:0 DeviceId:0]
./run.sh: line 14: 31271 Aborted                 (core dumped) ./run.out

CM error: Portable CM script failed (name = benchmark-program, return code = 256)
```

The last command I ran was:
```
cm run script --tags=run,mlperf,inference,generate-run-cmds,_submission,_short,_dashboard \
    --adr.python.name=mlperf-cuda \
    --adr.compiler.tags=gcc \
    --adr.openimages-preprocessed.tags=_500 \
    --submitter="Pablo-test-c++" \
    --lang=cpp \
    --hw_name=default \
    --model=retinanet \
    --backend=onnxruntime \
    --device=gpu \
    --scenario=Offline \
    --test_query_count=10 \
    --clean
```
