### ISSUE TITLE
MLPerf inference with tvm-onnx backend error

### ISSUE THREAD

**Issue by Ailurus1** [mlcommons/ck#575]
If I do each step according to tutorial on modularizing and automating MLPerf (part 3) using backend tvm-onnx then I get: 
> "CM error: no scripts were found with above tags and variations!"

Tried to roll back to the last commit in which there were any updates in the tutorial
```bash
cm pull repo mlcommons@ck --checkout=364cfa6
```
but then there was another error in attempt to build TVM after the same actions:
>make: No targets specified and no makefile found
>CM error: Portable CM script failed (return code = 256)

As I understood one of commands in the tutorial:
```bash
cm run script "install python-venv" --version=3.10.8 --name=mlperf
```
 is needed to install Python 3.10.8 to virtual environment, but in TVM documentation there is a limitation (https://tvm.apache.org/docs/install/from_source.html) "Avoid using Python 3.9.X+ which is not supported". So I made another attempt to run inference with Python 3.8.5 but as with the last updates as with roll back to 364cfa6 commit the result was the same as with Python 3.10.8

All the described actions were performed using WSL where I already had TVM built. There have also been attempts to run this on the docker container with clean Ubuntu 20.04:
In the latest version of cm with Python 3.8.5 there was the same error as in the first paragraph;
In the 364cfa6 all dependencies were successfully installed and built but after model compilation (there were many lines like INFO: te_compiler: Using X.cpu for Y based on highest priority (10)) I got:
>TVM compiled model: /tmp/model-tvm.so
>TVM: loading model /tmp/model-tvm.so

(the last line was output 4 times, probably because of threading as I have 4 CPU cores)
and I got possibly deadlock on these lines. At least two hours have passed in this state after which I pressed Ctrl+C. I also tried to do the same things after roll back to the commit when TVM first time appeared in the tutorial (78dbbe3) but the result remained the same. And after that I just tried to run inference one more time in the same container and finally it worked - everything loaded very quickly thanks to caching, there were the same lines with TVM: loading model /tmp/model-tvm.so, but there was no more deadlock and it finished correctly with expected benchmarks and display on wandb. Tried it again on both (364cfa6) and (78dbbe3) commits and it worked but similarly through a restart with Ctrl+C

**Comment by gfursin** [comment]
Thank you very much @Ailurus1 for your detailed report and feedback! Me and @arjunsuresh will check it tomorrow morning and will get back to you!

**Comment by arjunsuresh** [comment]
Thank you @Ailurus1 for raising the issue. The first issue (the main branch being broken) should be fixed once [this](https://github.com/mlcommons/ck/pull/573/commits/5459cd18e208b0c8d677a7cfe90da436a320226d) PR is merged. 

"(the last line was output 4 times, probably because of threading as I have 4 CPU cores)"
Yes, that's correct and is coming from the TVM backend. Ideally this should be cleaned up. 

"and I got possibly deadlock on these lines"
Yes, this also happened to us when we tried to run the TVM backend. First time the model is created, the run just hangs. When the model is loaded from /tmp it just works fine. Another tvm backend issue to be solved.

**Comment by gfursin** [comment]
> Thank you @Ailurus1 for raising the issue. The first issue (the main branch being broken) should be fixed once [this](https://github.com/mlcommons/ck/pull/573/commits/5459cd18e208b0c8d677a7cfe90da436a320226d) PR is merged.
> 
> "(the last line was output 4 times, probably because of threading as I have 4 CPU cores)" Yes, that's correct and is coming from the TVM backend. Ideally this should be cleaned up.
> 
> "and I got possibly deadlock on these lines" Yes, this also happened to us when we tried to run the TVM backend. First time the model is created, the run just hangs. When the model is loaded from /tmp it just works fine. Another tvm backend issue to be solved.

@arjunsuresh . I also suggest to pass this info to the TVM developers . CM can help them to automate and expose such issues across different software/hardware stacks ...

**Comment by Ailurus1** [comment]
Currently MLPerf Inference for ResNet50 with TVM-ONNX backend seems to work properly, so I think this issue can be closed
