### ISSUE TITLE
Simplify TVM installation

### ISSUE THREAD

**Issue by gfursin** [mlcommons/ck#580]
Hi @arjunsuresh.
Lets keep this ticket to keep track of the idea to simplify the ways of TVM installation in all CM workflows, i.e. keeping just one interface (get-tvm) and sub-packages to build it or install via PIP ...
Thanks!

**Comment by gfursin** [comment]
@arjunsuresh - I believe it's done now? By the way, do you mind to search for all _cm.json/_cm.yaml to check that we do not have old TVM tags (pip-install...), please? Thanks!

**Comment by arjunsuresh** [comment]
yes @gfursin . This is done now.

**Comment by gfursin** [comment]
Cool! Thanks a lot! I will close this ticket!
