### ISSUE TITLE
Add PIP installation for loadgen

### ISSUE THREAD

**Issue by gfursin** [mlcommons/ck#585]
As we discussed during the last MLPerf inference meeting, it will be useful to add PIP installation for MLPerf loadgen.  

@gaziqbal - let's sync on that since it can simplify our [CM automation workflow to run any ONNX model with loadgen](https://github.com/mlcommons/ck/tree/master/cm-mlops/script/app-loadgen-generic-python).

@arjunsuresh - we can also simplify our [CM script](https://github.com/mlcommons/ck/tree/master/cm-mlops/script/get-mlperf-inference-loadgen) to install loadgen via PIP instead of pulling the whole inference repo and building loadgen from there ... Let's discuss how to do it during our [next conf-call](https://github.com/mlcommons/ck/blob/master/docs/mlperf-education-workgroup.md).

CC @tjablin and @guschmue.

**Comment by arjunsuresh** [comment]
This is being done [here](https://github.com/mlcommons/inference/pull/1313)

**Comment by arjunsuresh** [comment]
This is the pypi release: https://pypi.org/project/mlperf-loadgen-cb

**Comment by gfursin** [comment]
@arjunsuresh . Hmm, this release looks very outdated (Mar 18, 2022). I would not recommend to use it unless it's regularly updated ...

**Comment by arjunsuresh** [comment]
Sorry. I shared wrong link. [This](https://github.com/mlcommons/inference/pull/1313) is the actual work. But I guess the official release is awaiting the code freeze for 3.1

**Comment by gfursin** [comment]
Cool. Thank you for the info @arjunsuresh . When it's published, we can add the support to our CM scripts! It will simplify dependencies ...

**Comment by arjunsuresh** [comment]
We do have it now.
```
pip install mlcommons-loadgen
```

But this pypi release is not yet managed automatically and so we may not have the latest loadgen here.
