### ISSUE TITLE
Automatically describing CM script input

### ISSUE THREAD

**Issue by gfursin** [mlcommons/ck#591]
Hi @arjunsuresh,

As we discussed yesterday, we need to add a key/dict to CM script meta to describe inputs.

We can use them when auto-generating READMEs as well as provide user-friendly help.

In fact, I think that we can try to overload --help in "cm run script" to add such info. It may require changes in CM core ...  I can check it later ...

Thanks!

**Comment by ctuning-admin** [comment]
We now have support to describe inputs from input_mapping ...
