### ISSUE TITLE
Add tests for TinyMLPerf

### ISSUE THREAD

**Issue by gfursin** [mlcommons/ck#597]
Based on the [user feedback](https://github.com/mlcommons/tiny_results_v1.0/issues/1), we should add basic tests to TinyMLPerf.
We can discuss it during the next conf-call of the MLCommons taskforce on education and reproducibility.

**Comment by arjunsuresh** [comment]
Sure Grigori. With the latest features of CM I think we can now determine the dependent folder paths of any script and add a github test for changes specific to those paths. This can reduce the number of tests for each PR and at the same time enable us to run more relevant tests.

**Comment by gfursin** [comment]
That will be useful, Arjun! We can discuss it during the next conf-call!

**Comment by gfursin** [comment]
CC @sahelib25

**Comment by ctuning-admin** [comment]
It's not our priority at this moment. I close this ticket.
