### ISSUE TITLE
Portable CM script failed (name = flash-tinyml-binary, return code = 256)

### ISSUE THREAD

**Issue by sahelib25** [mlcommons/ck#606]
Hi, I am trying to reproduce the tiny results v1.0 by OctoML and flash the microcontroller board but the following issue is triggered. Can anyone please help?
```
-- west flash: using runner openocd
-- runners.openocd: Flashing file: /home/saheli/CM/repos/local/cache/747a9e81fbc348e1/NUCLEO_L4R5ZI/ic/build/zephyr/zephyr.hex
Open On-Chip Debugger 0.11.0+dev-00244-g7e3dbbbe2 (2021-11-18-07:14)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
Info : The selected transport took over low-level target control. The results might differ compared to plain JTAG/SWD
Info : DEPRECATED target event trace-config
Info : clock speed 500 kHz
Error: open failed


FATAL ERROR: command exited with status 1: /home/saheli/CM/repos/local/cache/2fe55e8b2e5244ac/zephyr-sdk-0.13.2/sysroots/x86_64-pokysdk-linux/usr/bin/openocd -s /home/saheli/zephyrproject/zephyr/boards/arm/nucleo_l4r5zi/support -s /home/saheli/CM/repos/local/cache/2fe55e8b2e5244ac/zephyr-sdk-0.13.2/sysroots/x86_64-pokysdk-linux/usr/share/openocd/scripts -f /home/saheli/zephyrproject/zephyr/boards/arm/nucleo_l4r5zi/support/openocd.cfg -c init -c targets -c 'reset halt' -c 'flash write_image erase /home/saheli/CM/repos/local/cache/c948e587e6d445ec/NUCLEO_L4R5ZI/kws/build/zephyr/zephyr.hex' -c 'reset halt' -c 'verify_image /home/saheli/CM/repos/local/cache/c948e587e6d445ec/NUCLEO_L4R5ZI/kws/build/zephyr/zephyr.hex' -c 'reset run' -c shutdown

CM error: Portable CM script failed (name = flash-tinyml-binary, return code = 256)
```

**Comment by areusch** [comment]
hey @sahelib25, that looks like OpenOCD couldn't find your microcontroller board. is this running inside a docker container, and have you connected the microcontroller and updated your udev rules?

**Comment by sahelib25** [comment]
Hi @areusch, yes the microcontroller board was connected. But, I am not sure about the udev rules. Also, I did not use the docker container. Can you please help me with how I can update the udev rules?

**Comment by psyhtest** [comment]
@sahelib25 Is this running inside WSL?

**Comment by sahelib25** [comment]
@psyhtest, it is running on chai.

**Comment by areusch** [comment]
@sahelib25 try installing these udev rules, then unplugging/replugging the board: https://github.com/stlink-org/stlink/blob/develop/config/udev/rules.d/49-stlinkv2-1.rules

**Comment by psyhtest** [comment]
> @psyhtest, it is running on chai.

`chai` is a [Dell workstation](https://github.com/krai/ck-mlperf/blob/master/sut/chai/.cm/meta.json) (now running Ubuntu 22.04). (In the case of WSL, updating the udev rules might have been moot. I don't trust it when it comes to serial connections.)

**Comment by gfursin** [comment]
@arjunsuresh & @areusch - I think we should add these notes and CM instructions as a tutorial for the TinyMLPerf folks at https://github.com/mlcommons/ck/tree/master/docs/tutorials . What do you think? 

We can discuss it during the next conf-call of our taskforce on reproducibility or at the TinyMLPerf meeting...

**Comment by areusch** [comment]
@gfursin no objection and no discussion needed on my side as long as this solution fixes the problem. @sahelib25 can you let us know if that fixed your problem?

**Comment by gfursin** [comment]
Cool! Thank you @areusch!

**Comment by sahelib25** [comment]
Hi @areusch , it is still not working.

**Comment by sahelib25** [comment]
Hi @areusch, I have tried updating the udev rules once again. Now it is working fine. Thank you for your help.

**Comment by arjunsuresh** [comment]
@nefuy Can you please try?
```
cm run script --tags=get,dataset,imagenet-aux --env.CM_VERIFY_SSL=no
```

**Comment by arjunsuresh** [comment]
@nefuy  Can you please create a new issue explaining the issue as it does not seem connected to this particular issue?
