### ISSUE TITLE
Default variation "generic-preprocessor" specified for the group "preprocessing-source" with an already defined default variation "mlcommons-reference-preprocessor"

### ISSUE THREAD

**Issue by anandhu-eng** [mlcommons/ck#608]
Default variation "generic-preprocessor" specified for the group "preprocessing-source" with an already defined default variation "mlcommons-reference-preprocessor" error came while executing the command : cm run script --tags="app,mlcommons,mlperf,inference,tflite-cpp"

**Comment by arjunsuresh** [comment]
Fixed in [this commit](https://github.com/mlcommons/ck/commit/b818e17490dba2187f8652b575842a0958c8ff0f).
