### ISSUE TITLE
Test failure when python venv is used by CM

### ISSUE THREAD

**Issue by arjunsuresh** [mlcommons/ck#613]
We are seeing test failures like [this](https://github.com/mlcommons/ck/actions/runs/3841400314/jobs/6541573284) when python venv is picked as the python and the native python is built from the src as a shared library. Possible solution is to do the needed `LD_LIBRARY_PATH` export from the native python in the virtual env cache entry.

**Comment by gfursin** [comment]
I believe I've fixed the non-determinism: https://github.com/octoml/ck/commit/df6ee222c573c77b186dff6af7b9ebe86601a8e4
I will be checking the LD_LIBRARY_PATH issue now ...

**Comment by gfursin** [comment]
Fixed in the latest PR and merged with master
