### ISSUE TITLE
Seems like mechanism to reuse selection of sub-dependencies is not working well in some cases

### ISSUE THREAD

**Issue by gfursin** [mlcommons/ck#615]
I saw it on Ubuntu 22.04 but it should be universal. If we install 2 different python versions and then run image classification, let's say with onnx, we will be asked to select python version twice for the same dependency "get,python3" while normally the first selection should be reused:

```bash
cm run script "get python" --version=3.11.1
cm run script "get python" --version=3.10.7
cm run script "python app image-classification onnx"
```

**Comment by arjunsuresh** [comment]
Hi @gfursin I tried the same on Ubuntu 22.04 and not able to reproduce this issue. The selection prompt came only once.

**Comment by gfursin** [comment]
Hmm, thank you for the report @arjunsuresh . Let me check it with the "clean" installation ...

**Comment by gfursin** [comment]
I believe it's fixed with the latest updates. I close this ticket.
