### ISSUE TITLE
Universal file-download CM script

### ISSUE THREAD

**Issue by arjunsuresh** [mlcommons/ck#621]
We currently have a download function in CM which can download any file similar to wget. If the downloaded file is a zip or tar file, we currently extract them in individual `customize.py` files. It would be cleaner if we make a `download-file` cm script which internally calls this download function and does any needed extraction of the downloaded files. This `download-file` cm script can then be added as a `pre_hook_deps` to other CM scripts replacing the current redundant codes there.

**Comment by gfursin** [comment]
I agree. Just let's make sure that it's portable across all platforms including Windows!
Thank you!

**Comment by arjunsuresh** [comment]
Hi @gfursin , I have made a prototype for this [here](https://github.com/ctuning/mlcommons-ck/blob/master/cm-mlops/script/download-and-extract/customize.py). This is expected to handle all downloads and extractions with checksum checks for validation so that users do not face any issue due to broken downloads. But to make this work on windows we probably need to redo all the commands - they are not a lot though.

**Comment by gfursin** [comment]
It will be very useful! Thank you very much @arjunsuresh . But we should support Windows too ;) - I can check it at some point ...

**Comment by gfursin** [comment]
I added support on Windows and it seems to be working fine now. I close this ticket.
