### ISSUE TITLE
MLPerf submission system information "host_processor_core_count" incorrect

### ISSUE THREAD

**Issue by mgoin** [mlcommons/ck#623]
Following the command at [`docs/tutorials/mlperf-language-processing.md`](https://github.com/mlcommons/ck/blob/e1d8f15cc27fad763a3dbc629b0f3a61f7a5e0ff/docs/tutorials/mlperf-language-processing.md), I was able to record a test submission. This worked great.

Looking at the system information most looked reasonable except that I expect `host_processor_core_count` to correspond to the number of physical cores. Currently it seems to measure the number of threads. On a 2P Xeon Platinum 8380 it records 160 cores when I expect to see 80.

```
  "host_processor_caches": "L1d cache: 3.8 MiB (80 instances), L1i cache: 2.5 MiB (80 instances), L2 cache: 100 MiB (80 instances), L3 cache: 120 MiB (2 instances)",
  "host_processor_core_count": "160",
  "host_processor_frequency": "3400.0000",
  "host_processor_interconnect": "",
  "host_processor_model_name": "Intel(R) Xeon(R) Platinum 8380 CPU @ 2.30GHz",
  "host_processors_per_node": "2",
  "host_storage_capacity": "7.5T",
  "host_storage_type": "",
  "hw_notes": "",
```

**Comment by arjunsuresh** [comment]
Thank you @mgoin for reporting this issue. It should be fixed in the latest commit.
