### ISSUE TITLE
Testing that CM script can write in the current directory

### ISSUE THREAD

**Issue by gfursin** [mlcommons/ck#630]
While improving CUDA detection based on feedback from @michaelclesi, we have encountered the issue: when CM scripts run in the write-only directory (such as /usr ...) CM fails to create tmp files in the current directory. This mechanism is important because of CM workflow concept to record and update files in the current or cached directory. We just need to add a test in the root script that we can write in the current directory and fail in the user-friendly way ;) ...

@arjunsuresh - let me check it ...

**Comment by gfursin** [comment]
Fixed in https://github.com/octoml/ck/commit/5af12d89ade1302a4f338ed952a2ee4255bc51b6 . @arjunsuresh, do you mind to check if it works fine on your machine? You can go to /usr and try to run any script ;) ... Thanks! If it's fine, we will merge it with the mainline MLCommons repo in the next PR (together with your CUDA detection fixes)...

**Comment by arjunsuresh** [comment]
Hi Grigori, it works fine :)

**Comment by gfursin** [comment]
Thanks!
