### ISSUE TITLE
Switch to token based auth or SSH when pushing to Github

### ISSUE THREAD

**Issue by Adityashaw** [mlcommons/ck#691]
Github doesn't support  (username + password) anymore for push command.

https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/

Issue found when trying the `Generate actual submission tree` command from

https://github.com/mlcommons/ck/blob/master/cm-mlops/script/run-mlperf-inference-mobilenet-models/README-about.md#generate-actual-submission-tree

**Comment by arjunsuresh** [comment]
Thank you @Adityashaw for raising this issue. Actually we do support both token and SSH Github URLs. This is the [code](https://github.com/mlcommons/ck/blob/master/cm-mlops/automation/script/module.py#L3363) for it.

* If `env['CM_GH_TOKEN']=TOKEN_VALUE` is set then git URLs are changed to add this token. 
* If `env['CM_GIT_SSH']=yes`, then git URLs are chnged to SSH.

**Comment by arjunsuresh** [comment]
Thank you @Adityashaw It is now added in our [script README](https://github.com/ctuning/mlcommons-ck/blob/master/cm-mlops/script/README.md#special-env-keys) which is still a WIP.
