### ISSUE TITLE
 Load model from resnext50_32x4d_fpn.onnx failed:Protobuf parsing failed.

### ISSUE THREAD

**Issue by marf-cn** [mlcommons/ck#744]
Hi,I am reproducing the [1st part](https://github.com/mlcommons/ck/blob/master/docs/tutorials/sc22-scc-mlperf.md): customize MLPerf inference (Python ref implementation, Open images, ONNX, CPU)

`cm run script "app mlperf inference generic _python _retinanet _onnxruntime _cpu"      --scenario=Offline      --mode=accuracy      --test_query_count=10      --rerun`

it reports error

```
INFO:main:Namespace(dataset='openimages-800-retinanet-onnx', dataset_path='/home/mlperf/CM/repos/local/cache/ec5967bedbaf49e9', dataset_list='/home/mlperf/CM/repos/local/cache/ec5967bedbaf49e9/annotations/openimages-mlperf.json', data_format=None, profile='retinanet-onnxruntime', scenario='Offline', max_batchsize=1, model='/home/mlperf/CM/repos/local/cache/4d2c1a02a1274cc4/resnext50_32x4d_fpn.onnx', output='/home/mlperf/test_results/1f949640c9a2-reference-cpu-onnxruntime-v1.14.1-default_config/retinanet/offline/accuracy', inputs=['images'], outputs=['boxes', 'labels', 'scores'], backend='onnxruntime', model_name='retinanet', threads=16, qps=None, cache=0, cache_dir='/home/mlperf/CM/repos/local/cache/ec5967bedbaf49e9', preprocessed_dir=None, use_preprocessed_dataset=True, accuracy=True, find_peak_performance=False, debug=False, mlperf_conf='/home/mlperf/CM/repos/local/cache/eae1c29975bd4190/inference/mlperf.conf', user_conf='/home/mlperf/CM/repos/mlcommons@ck/cm-mlops/script/generate-mlperf-inference-user-conf/tmp/618fa49445834fc7af04f6b4ab46b17e.conf', audit_conf='audit.config', time=None, count=10, performance_sample_count=None, max_latency=None, samples_per_query=8)
INFO:coco:loaded 10 images, cache=0, already_preprocessed=True, took=0.0sec
Traceback (most recent call last):
  File "/home/mlperf/CM/repos/local/cache/eae1c29975bd4190/inference/vision/classification_and_detection/python/main.py", line 615, in <module>
    main()
  File "/home/mlperf/CM/repos/local/cache/eae1c29975bd4190/inference/vision/classification_and_detection/python/main.py", line 494, in main
    model = backend.load(args.model, inputs=args.inputs, outputs=args.outputs)
  File "/home/mlperf/CM/repos/local/cache/eae1c29975bd4190/inference/vision/classification_and_detection/python/backend_onnxruntime.py", line 41, in load
    self.sess = rt.InferenceSession(model_path, opt, providers=["CPUExecutionProvider"])
  File "/home/mlperf/.local/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 360, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/mlperf/.local/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 397, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from /home/mlperf/CM/repos/local/cache/4d2c1a02a1274cc4/resnext50_32x4d_fpn.onnx failed:Protobuf parsing failed.

CM error: Portable CM script failed (name = benchmark-program, return code = 256)

Note that it is often a portability problem of the third-party tool or native script that is wrapped and unified by this CM script.
The CM concept is to collaboratively fix such issues inside portable CM scripts to make existing tools and native script more portable, interoperable, deterministic and reproducible.
```

**Comment by arjunsuresh** [comment]
Hi @marf-cn can you please share the output of the below command?
```
cm run script --tags=detect,os --json
```

**Comment by marf-cn** [comment]
here is output
mlperf@272e049116b3:~$ cm run script --tags=detect,os --json

* Searching for collective script(s) with tags "detect,os"
  - Number of scripts found: 1
  - Found script::detect-os,863735b7db8c44fc in /home/mlperf/CM/repos/mlcommons@ck/cm-mlops/script/detect-os
  - Running preprocess ...

  - Running native script "/home/mlperf/CM/repos/mlcommons@ck/cm-mlops/script/detect-os/run.sh" from temporal script "tmp-run.sh" in "/home/mlperf" ...

  - Running postprocess ...
  - running time of script "detect-os,detect,os,info": 0.26 sec.

{
  "return": 0,
  "env": {
    "CM_HOST_OS_TYPE": "linux",
    "CM_HOST_OS_BITS": "64",
    "CM_HOST_OS_FLAVOR": "ubuntu",
    "CM_HOST_OS_FLAVOR_LIKE": "debian",
    "CM_HOST_OS_VERSION": "22.04",
    "CM_HOST_OS_KERNEL_VERSION": "5.15.0-71-generic",
    "CM_HOST_OS_GLIBC_VERSION": "2.35",
    "CM_HOST_OS_MACHINE": "x86_64",
    "CM_HOST_OS_PACKAGE_MANAGER": "apt",
    "CM_HOST_OS_PACKAGE_MANAGER_INSTALL_CMD": "apt-get install -y",
    "CM_HOST_OS_PACKAGE_MANAGER_UPDATE_CMD": "apt-get update -y",
    "+CM_HOST_OS_DEFAULT_LIBRARY_PATH": [
      "/usr/local/lib/x86_64-linux-gnu",
      "/lib/x86_64-linux-gnu",
      "/usr/lib/x86_64-linux-gnu",
      "/usr/lib/x86_64-linux-gnu64",
      "/usr/local/lib64",
      "/lib64",
      "/usr/lib64",
      "/usr/local/lib",
      "/lib",
      "/usr/lib",
      "/usr/x86_64-linux-gnu/lib64",
      "/usr/x86_64-linux-gnu/lib"
    ],
    "CM_HOST_PLATFORM_FLAVOR": "x86_64",
    "CM_HOST_PYTHON_BITS": "64",
    "CM_HOST_SYSTEM_NAME": "272e049116b3"
  },
  "new_env": {
    "CM_HOST_OS_TYPE": "linux",
    "CM_HOST_OS_BITS": "64",
    "CM_HOST_OS_FLAVOR": "ubuntu",
    "CM_HOST_OS_FLAVOR_LIKE": "debian",
    "CM_HOST_OS_VERSION": "22.04",
    "CM_HOST_OS_KERNEL_VERSION": "5.15.0-71-generic",
    "CM_HOST_OS_GLIBC_VERSION": "2.35",
    "CM_HOST_OS_MACHINE": "x86_64",
    "CM_HOST_OS_PACKAGE_MANAGER": "apt",
    "CM_HOST_OS_PACKAGE_MANAGER_INSTALL_CMD": "apt-get install -y",
    "CM_HOST_OS_PACKAGE_MANAGER_UPDATE_CMD": "apt-get update -y",
    "+CM_HOST_OS_DEFAULT_LIBRARY_PATH": [
      "/usr/local/lib/x86_64-linux-gnu",
      "/lib/x86_64-linux-gnu",
      "/usr/lib/x86_64-linux-gnu",
      "/usr/lib/x86_64-linux-gnu64",
      "/usr/local/lib64",
      "/lib64",
      "/usr/lib64",
      "/usr/local/lib",
      "/lib",
      "/usr/lib",
      "/usr/x86_64-linux-gnu/lib64",
      "/usr/x86_64-linux-gnu/lib"
    ],
    "CM_HOST_PLATFORM_FLAVOR": "x86_64",
    "CM_HOST_PYTHON_BITS": "64",
    "CM_HOST_SYSTEM_NAME": "272e049116b3"
  },
  "state": {
    "os_uname_machine": "x86_64",
    "os_uname_all": "Linux 272e049116b3 5.15.0-71-generic #78~20.04.1-Ubuntu SMP Wed Apr 19 11:26:48 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux"
  },
  "new_state": {
    "os_uname_machine": "x86_64",
    "os_uname_all": "Linux 272e049116b3 5.15.0-71-generic #78~20.04.1-Ubuntu SMP Wed Apr 19 11:26:48 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux"
  },
  "deps": []
}

**Comment by arjunsuresh** [comment]
I just tried on a similar docker and it ran fine. I guess there could be some issue with the installed protobuf version or the model download wasn't completed successfully. Can you please do 
```
rm -rf /home/mlperf/CM/repos/local/cache/4d2c1a02a1274cc4/
```

and then repeat the command?

**Comment by marf-cn** [comment]
Thank you, @arjunsuresh, I tried the command, it works!
