### ISSUE TITLE
Issue with running on WSL2

### ISSUE THREAD

**Issue by nijoj** [mlcommons/ck#795]
OS details (Ubuntu on WSL)
  OS Name: Microsoft Windows 11 Home Single Language
  WSL version: 1.2.5.0
  Kernel version: 5.15.90.1
  WSLg version: 1.0.51
  MSRDC version: 1.2.3770
  Direct3D version: 1.608.2-61064218
  DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
  Windows version: 10.0.22621.1702

Distro Version
  Distributor ID: Ubuntu
  Description:    Ubuntu 22.04.2 LTS
  Release:        22.04
  Codename:       jammy

Repro Steps

1. Follow the readme : https://github.com/mlcommons/ck/blob/master/cm-mlops/script/run-mlperf-inference-mobilenet-models/README-about.md
2. Run the command `cm run script --tags=run,mobilenet-models,_tflite,_find-performance` under WSL2 (Ubuntu) on windows

Logs
```Configuration finished
/home/nijo/CM/repos/local/cache/61e8cb4356594425/install/bin/bazel build -c opt --define tflite_with_xnnpack=true //tensorflow/lite:libtensorflowlite.so
ERROR: The project you're trying to build requires Bazel 6.1.0 (specified in /home/nijo/CM/repos/local/cache/46d29e82360e4be6/src/.bazelversion), but it wasn't found in /home/nijo/CM/repos/local/cache/61e8cb4356594425/install/bin.

Bazel binaries for all official releases can be downloaded from here:
  https://github.com/bazelbuild/bazel/releases

You can download the required version directly using this command:
  (cd "/home/nijo/CM/repos/local/cache/61e8cb4356594425/install/bin" && curl -fLO https://releases.bazel.build/6.1.0/release/bazel-6.1.0-linux-x86_64 && chmod +x bazel-6.1.0-linux-x86_64)
{'return': 2, 'error': 'Portable CM script failed (name = install-tensorflow-from-src, return code = 256)\n\nNote that it is often a portability problem of the third-party tool or native script that is wrapped and unified by this CM script.\nThe CM concept is to collaboratively fix such issues inside portable CM scripts to make existing tools and native script more portable, interoperable, deterministic and reproducible.\n\nPlease help the community by reporting the full log with the command line here:\n* https://github.com/mlcommons/ck/issues \n* https://cKnowledge.org/mlcommons-taskforce\n\nThank you'}
```

Full logs : https://pastebin.com/bK5Uq9bs

Expected Behavior
Script to run successfully

Actual Behavior
- Script keeps looping on the prompt questions with the above error
- Had to install clang separately outside the script
- Fixed by running the command ` cd "/home/nijo/CM/repos/local/cache/61e8cb4356594425/install/bin" && curl -fLO https://releases.bazel.build/6.1.0/release/bazel-6.1.0-linux-x86_64 && chmod +x bazel-6.1.0-linux-x86_64
` directly and then running the script again

@arjunsuresh

**Comment by arjunsuresh** [comment]
Thank you @nijoj for reporting this issue. Tensorflow-src master branch now needs bazel 6.1.0 and I have fixed this issue [here[(https://github.com/mlcommons/ck/commit/a9dece7d34c49f778eb957159a6d8ac72444baab).
