### ISSUE TITLE
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by anandhu-eng** [mlcommons/ck#828]
System: Ubuntu 22.04 on Docker (windows)

This error came while invoking loadgen during mlperf inference testing

Fixed by installing packages with the following command:
sudo apt-get install ffmpeg libsm6 libxext6  -y

**Comment by arjunsuresh** [comment]
I believe this might have happened because of `get-sys-utils-cm` installation being skipped or failed. But we can probably add this package as a direct dependency of loadgen.

**Comment by anandhu-eng** [comment]
Okay thanks 🤝

**Comment by anandhu-eng** [comment]
But upon checking `get-sys-utils-cm`, i did not find these three libraries (ffmpeg libsm6 libxext6) listed in `run-ubuntu.sh`

**Comment by arjunsuresh** [comment]
[libgli1](https://github.com/mlcommons/ck/blob/master/cm-mlops/script/get-sys-utils-cm/run-ubuntu.sh#L52) is the alternative package that provides libGL.so.1. Can you please confirm why `get-generic-sys-utils` did not get executed?

**Comment by anandhu-eng** [comment]
Sure @arjunsuresh , I think the same problem raised in case of sudo and curl. Let me check and confirm.

**Comment by arjunsuresh** [comment]
I believe this is fixed now
