### ISSUE TITLE
No package Sudo and Curl

### ISSUE THREAD

**Issue by anandhu-eng** [mlcommons/ck#829]
The error came while doing mlperf inference submission. 
System: Ubuntu 22.03 on Docker (windows)

Fixed by manually installing Sudo and Curl using:
apt install sudo curl

**Comment by arjunsuresh** [comment]
These packages are part of [generic-sys-utils](https://github.com/mlcommons/ck/blob/master/cm-mlops/script/get-sys-utils-cm/run-ubuntu.sh#L52). Was the installation of generic-sys-utils skipped?

**Comment by gfursin** [comment]
I believe it's fixed now.
