### ISSUE TITLE
Missing parameter values in tflite_cpp-cpu-tflite-vmaster-default_config.json

### ISSUE THREAD

**Issue by anandhu-eng** [mlcommons/ck#830]
System: Ubuntu 22.03 run on docker (windows)

Error came while running mlperf inference submission

system_type_detail and  host_networking_card_count was not automatically added to the json file.

Fix:
Added both parameters manually to the json file.
"system_type_detail":"laptop",
"host_networking_card_count": "1"

**Comment by arjunsuresh** [comment]
Hi @anandhu-eng Can you please do 
```
cm pull repo mlcommons@ck
```
and then retry [this command](https://github.com/mlcommons/ck/tree/master/cm-mlops/script/run-mlperf-inference-mobilenet-models#generate-actual-submission-tree)

**Comment by anandhu-eng** [comment]
Still error persists

![image](https://github.com/mlcommons/ck/assets/71482562/3a3ef1a3-d2d4-40ea-807c-6837b34578de)

**Comment by anandhu-eng** [comment]
Should i clear any cache and rerun?

**Comment by arjunsuresh** [comment]
Hi @anandhu-eng There was some caching in the script and that should be why this happened. Can you please try with the latest code in the CM repo? this issue should be resolved now.

**Comment by anandhu-eng** [comment]
Sure, I will try after the current accuracy and performance tests are over for ubuntu 23.04

**Comment by arjunsuresh** [comment]
I believe this is fixed now.
