### ISSUE TITLE
Running latest MLPerf inference on MacOS asks for GCC and breaks

### ISSUE THREAD

**Issue by gfursin** [mlcommons/ck#836]
I think we added GCC as a default variation in the latest MLPerf inference CM workflow. I think we should remove it and keep LLVM by default. We can still force GCC via deps flags ...

**Comment by arjunsuresh** [comment]
Hi @gfursin , I think we need to use `llvm` as the default for macOS and `gcc` for Linux. Also, we probably need to separate gcc and g++ or combine them for C/C++ compiler. clang and llvm also need to be separated out as clang is an optional project in llvm.
