### ISSUE TITLE
Error when username contains space in path - Windows 11

### ISSUE THREAD

**Issue by anandhu-eng** [mlcommons/ck#849]
![image](https://github.com/mlcommons/ck/assets/71482562/b07b53d8-f1d4-4f14-8efd-4bdeb1823ca0)

Faced the same situation recently where I solved by placing the path in inverted quotes.

![image](https://github.com/mlcommons/ck/assets/71482562/aed54ce2-4b8c-48ae-a318-23659521be2b)

**Comment by gfursin** [comment]
Yes, I confirm the issue. Reproduced it and will check how to fix it ... We need to add "" on Windows when calling scripts ...

**Comment by gfursin** [comment]
I believe it's fixed in the last commit ... @anandhu-eng - do you mind to check it on your system? Thanks a lot!

**Comment by gfursin** [comment]
I believe it works. If there is a new issue, we can reopen this ticket.
