### ISSUE TITLE
Collecting feedback from ACM/IEEE MICRO'23 authors to improve CM automation

### ISSUE THREAD

**Issue by gfursin** [mlcommons/ck#945]

**Comment by gfursin** [comment]
1) need to provide specs of `_cm.yaml` of CM scripts (https://github.com/mlcommons/ck/blob/master/docs/specs/cm-automation-script.md) and how to pass keys and ENV to sub dependencies

**Comment by gfursin** [comment]
https://github.com/mlcommons/ck/issues/941

**Comment by gfursin** [comment]
Need FAQ about CM scripts ...

**Comment by neel-patel-1** [comment]
`--local_path` option still results in downloading of remote file in spite of local  resouce's being available:

```
- tags: download,file,_url.https://spec2017iso.s3.us-east-2.amazonaws.com/cpu2017-1_0_5.iso
  env:
    CM_DOWNLOAD_FINAL_ENV_NAME: 'SPEC_ISO'
  extra_cache_tags: micro23,artifact,ae,xfm,spec
  force_cache: true
```
Still results in downloading the file in spite of the local path to the resource being provided

```
(cm) n869p538@bristol:reproduce-paper-m2023-xfm$ cmr "reproduce project micro-2023 xfm _install_spec_deps" 
* cm run script "reproduce project micro-2023 xfm _install_spec_deps"
  * cm run script "detect os"
  * cm run script "get python" 
  * cm run script "get generic-python-lib _pandas"
  * cm run script "get generic-python-lib _matplotlib"
  * cm run script "get git repo _repo.https://github.com/neel-patel-1/XFM_MICRO2023"
  * cm run script "download file _url.https://spec2017iso.s3.us-east-2.amazonaws.com/cpu2017-1_0_5.iso"

Downloaded:   4%
```

**Comment by gfursin** [comment]
> `--local_path` option still results in downloading of remote file in spite of local resouce's being available:
> 
> ```
> - tags: download,file,_url.https://spec2017iso.s3.us-east-2.amazonaws.com/cpu2017-1_0_5.iso
>   env:
>     CM_DOWNLOAD_FINAL_ENV_NAME: 'SPEC_ISO'
>   extra_cache_tags: micro23,artifact,ae,xfm,spec
>   force_cache: true
> ```
> 
> Still results in downloading the file in spite of the local path to the resource being provided
> 
> ```
> (cm) n869p538@bristol:reproduce-paper-m2023-xfm$ cmr "reproduce project micro-2023 xfm _install_spec_deps" 
> * cm run script "reproduce project micro-2023 xfm _install_spec_deps"
>   * cm run script "detect os"
>   * cm run script "get python" 
>   * cm run script "get generic-python-lib _pandas"
>   * cm run script "get generic-python-lib _matplotlib"
>   * cm run script "get git repo _repo.https://github.com/neel-patel-1/XFM_MICRO2023"
>   * cm run script "download file _url.https://spec2017iso.s3.us-east-2.amazonaws.com/cpu2017-1_0_5.iso"
> 
> Downloaded:   4%
> ```

Thanks for your feedback! CC @arjunsuresh

**Comment by arjunsuresh** [comment]
@neel-patel-1 can you please share how exactly you added `--local_path` option?

**Comment by neel-patel-1** [comment]
(cm) n869p538@bristol:reproduce-paper-m2023-xfm$ cmr "download file _url.https://spec2017iso.s3.us-east-2.amazonaws.com/cpu2017-1_0_5.iso" --local_path=/home/n869p538/cpu2017-1_0_5.iso

**Comment by neel-patel-1** [comment]
@arjunsuresh  The command sequence looked as follows:
>```
> cmr "download file _url.https://spec2017iso.s3.us-east-2.amazonaws.com/cpu2017-1_0_5.iso" --local_path=/home/n869p538/cpu2017-1_0_5.iso
>```

> ```
> (cm) n869p538@bristol:reproduce-paper-m2023-xfm$ cmr "reproduce project micro-2023 xfm _install_spec_deps" 
> * cm run script "reproduce project micro-2023 xfm _install_spec_deps"
>   * cm run script "detect os"
>   * cm run script "get python" 
>   * cm run script "get generic-python-lib _pandas"
>   * cm run script "get generic-python-lib _matplotlib"
>   * cm run script "get git repo _repo.https://github.com/neel-patel-1/XFM_MICRO2023"
>   * cm run script "download file _url.https://spec2017iso.s3.us-east-2.amazonaws.com/cpu2017-1_0_5.iso"
> 
> Downloaded:   4%
> ```

**Comment by neel-patel-1** [comment]
Turning on cache explicitly works. 

The desired behavior was to allow the user to specify the path to their local version of the resource before continuing with the artifact reproduction process

This command seems to have the desired behavior:
```
cmr "download file _url.https://spec2017iso.s3.us-east-2.amazonaws.com/cpu2017-1_0_5.iso" --local_path=/home/n869p538/cpu2017-1_0_5.iso --force_cache=true
```

Thanks for your help
