### ISSUE TITLE
Feature request: Script elapsed time

### ISSUE THREAD

**Issue by WarrenSchultz** [mlcommons/ck#955]
When testing multiple models, datasets, and machines, it would be handy to have an elapsed time for script completion.
It would really help when budgeting time and determining when something has gone on longer than it should.

Thanks!

**Comment by arjunsuresh** [comment]
Hi @WarrenSchultz thank you for your feedback. Do you have an example output for this?

**Comment by gfursin** [comment]
I believe I added this functionality to CM scripts some time ago. Flag `--time` should print elapsed time for script completion. I close this ticket and we can reopen it in cm4mlops if needed.
