### ISSUE TITLE
how to cleanup before re-running a test

### ISSUE THREAD

**Issue by jdesfossez** [mlcommons/ck#984]
Hi,

I have followed the doc to the point where I can run the first example of the Bert test with CUDA:
https://github.com/mlcommons/ck/blob/master/docs/mlperf/inference/bert/README_nvidia.md

```
cmr "generate-run-cmds inference _find-performance _all-scenarios" \
--model=bert-99 --implementation=nvidia-original --device=cuda --backend=tensorrt \
--category=edge --division=open --quiet
```

It seems to work, I see the GPU is busy for a while (probably around 30+ minutes)
But when it completes, if I re-run the exact same command, it completes in about 40 seconds and all the results are marked as INVALID.

So my question is if we need to run some kind of cleanup command between runs or if I am encountering a bug somewhere.

I have attached a small portion of the output, I see an error in there, but I don't know if it's fatal
[bert-log.txt](https://github.com/mlcommons/ck/files/13125398/bert-log.txt)

Thanks !

Julien

**Comment by jdesfossez** [comment]
Follow-up, I deleted the last folder (modified by date) in `CM/repos/local/cache/` and re-ran the command and it is now running as expected.
Is there a clean way to do this ?

**Comment by arjunsuresh** [comment]
Oh, actually there is a `--rerun` flag to force rerun even when results exist. Can you please try it?

**Comment by jdesfossez** [comment]
Hum it doesn't seem to work with this command.

**Comment by arjunsuresh** [comment]
```
cmr "generate-run-cmds inference _submission _all-scenarios" --model=bert-99 \
--device=cuda --implementation=nvidia-original --backend=tensorrt \
--execution-mode=valid --results_dir=$HOME/results_dir \
--category=edge --division=open --quiet --rerun
```

This should be the command to get a valid result. If the estimated `target_qps` is incorrect you can also provide `--offline_target_qps=<ACTUAL_VALUE>` to get a valid run. A run is valid only if it runs for 10 minutes and how long the benchmark run (in offline scenario) is determined by the given/estimated target_qps value.

**Comment by jdesfossez** [comment]
Ah yes, I think this is what I was missing, it is now running and it looks busy as expected.
Thank you !
